ida-arbeitszeit/arbeitszeitapp

- LICENSE
- README.rst
- setup.cfg
I added the license file for AGPLv3 to the repository.
> Add license file

- arbeitszeit_flask/company/routes.py
- arbeitszeit_flask/dependency_injection/__init__.py
- arbeitszeit_flask/templates/company/profile.html
- arbeitszeit_flask/templates/member/profile.html
- arbeitszeit_web/get_member_profile_info.py
- flake.nix
- tests/presenters/test_get_member_profile_info_presenter.py
- type_stubs/flask_login.pyi
This PR makes the profile pages for members and companies translatable.
PlanID: 1906a785-a23b-44b3-a599-96ee43dd388c
> Translate profile page

- arbeitszeit_flask/templates/macros.html
- arbeitszeit_flask/translations/de/LC_MESSAGES/messages.po
- arbeitszeit_flask/translations/en/LC_MESSAGES/messages.po
I updated the german translations. In the process I found a typo which was corrected.
No payment necessary.
> Update german translations

- arbeitszeit_flask/templates/member/pay_consumer_product.html
> Translate template member/pay_consumer_product.html

- arbeitszeit_flask/templates/member/my_purchases.html
- arbeitszeit_flask/translations/de/LC_MESSAGES/messages.po
- arbeitszeit_flask/translations/en/LC_MESSAGES/messages.po
> Update german translation files

- arbeitszeit_flask/templates/company/account_p.html
- arbeitszeit_flask/templates/company/list_all_transactions.html
- arbeitszeit_flask/templates/company/my_purchases.html
- arbeitszeit_flask/templates/company/plan_summary.html
- arbeitszeit_flask/templates/company/transfer_to_company.html
- arbeitszeit_flask/templates/macros/coop_summary.html
Making six more files from list in #312 translatable.
Plan-ID: e8e5c56f-9e2d-497d-a896-a26bc41e1c16
> Make more strings translatable

- arbeitszeit_flask/templates/base_company.html
- arbeitszeit_flask/templates/macros/list_messages.html
- arbeitszeit_flask/templates/member/statistics.html
This change deals exclusively with translations of user facing strings. All other changes are only formatting changes to the source file without any runtime implications.
> Update translations for base_company and list_messages templates

- arbeitszeit_flask/dependency_injection/__init__.py
- arbeitszeit_flask/forms.py
- arbeitszeit_web/hide_plan.py
- arbeitszeit_web/pay_means_of_production.py
- arbeitszeit_web/query_plans.py
- arbeitszeit_web/show_r_account_details.py
- tests/presenters/test_hide_plan_presenter.py
- tests/presenters/test_pay_means_of_production_presenter.py
- tests/presenters/test_query_plans_presenter.py
- tests/presenters/test_show_r_account_details.py
Making user facing strings in four more presenters translatable.
Plan ID: e8e5c56f-9e2d-497d-a896-a26bc41e1c16
> Making strings translatable

- flake.lock
- requirements.txt
This PR updates the nixpkgs revision that is used and also the `requirements.txt` file.
> Update (nix) dependencies

- tests/presenters/dependency_injection.py
- tests/presenters/test_send_work_certificates_to_worker_presenter.py
- tests/presenters/test_show_company_work_invite_details_presenter.py
- tests/presenters/test_show_my_accounts_presenter.py
- tests/presenters/test_show_my_plans_presenter.py
- tests/presenters/test_show_p_account_details.py
- tests/presenters/test_show_prd_account_details_presenter.py
- tests/presenters/test_show_r_account_details.py
- tests/presenters/test_user_action_resolver.py
- tests/presenters/url_index.py
This PR refactors all of the remaining presenter tests to use dependency injection.
> Refactor all remaining presenter tests to use dependency injection

- .github/workflows/python-app.yml
- Makefile
- README.rst
- docs/conf.py
- docs/index.rst
- docs/modules/arbeitszeit.rst
- docs/modules/arbeitszeit.use_cases.pay_consumer_product.rst
- docs/modules/arbeitszeit.use_cases.rst
- docs/modules/arbeitszeit_flask.auth.rst
- docs/modules/arbeitszeit_flask.company.rst
- docs/modules/arbeitszeit_flask.database.rst
- docs/modules/arbeitszeit_flask.dependency_injection.rst
- docs/modules/arbeitszeit_flask.member.rst
- docs/modules/arbeitszeit_flask.rst
- docs/modules/arbeitszeit_flask.views.rst
- docs/modules/arbeitszeit_web.controllers.rst
- docs/modules/arbeitszeit_web.presenters.rst
- docs/modules/arbeitszeit_web.rst
- docs/modules/modules.rst
- docs/philosophy.rst
- flake.nix
- make.bat
- regenerate-api-docs
- requirements.txt
- update-requirements-from-nix
The instructions to build the development documentation can be found in the README.
> Implement first version of development documentation

- arbeitszeit_flask/auth/routes.py
- arbeitszeit_flask/dependency_injection/__init__.py
- arbeitszeit_flask/dependency_injection/views.py
- arbeitszeit_flask/views/signup_company_view.py
- arbeitszeit_web/presenters/register_company_presenter.py
- arbeitszeit_web/register_company.py
- arbeitszeit_web/session.py
- tests/dependency_injection.py
- tests/presenters/dependency_injection.py
- tests/presenters/test_register_company_presenter.py
- tests/session.py
I refactored the route /company/signup similarly to the route /member/signup,
> Refactor /company/signup

- arbeitszeit_flask/company/routes.py
- arbeitszeit_flask/views/pay_means_of_production.py
fixes #325
fixes #326
This PR should fix both form issues when paying means of production. 
@seppeljordan please confirm that issue #326 is fixed for you as well.
(please add this plan to our cooperation as well)
> render transfer_to_company w/ empty form when GET

- arbeitszeit/use_cases/get_company_summary.py
- arbeitszeit_flask/templates/macros/company_summary.html
- arbeitszeit_web/get_company_summary.py
- tests/presenters/test_get_company_summary_presenter.py
- tests/use_cases/test_get_company_summary.py
fixes #374
This PR proposes some improvements around the metrics shown in company summary page. Besides optical changes, it introduces a relative deviation of "infinite" (see issue description for problem description).
Plan ID: 6f2e3f6-233a-4ef1-a1a0-39c5d411b38c
> Improve-metrics-in-company_summary

- README.rst
A overview/introduction has been added to README. 
Also some restructuring has been done. There are now three main sections: Overview, Development, License. 
Plan-ID: ed6eb89f-0633-4544-9ddc-94466b7d5e82
> Changes to README

- README.rst
fixes #442
see issue.
No certificates needed.
> adapt README to inform devs to use localhost

- arbeitszeit_flask/templates/company/account_prd.html
- arbeitszeit_flask/templates/company/list_all_transactions.html
- arbeitszeit_flask/templates/macros/transactions.html
The company's prd account html and all-transactions html were still to be redesigned/made responsive. This is done in this PR. 
Plan-ID: ecdb2bb1-6690-4a6e-a8a5-d08e26ac1afd
> Redesign prd and all transactions view

- arbeitszeit_flask/templates/macros/start_hilfe.html
I propose a user manual in this Pull Request. It's written in HTML as part of Arbeitszeitapp and it would replace the text in the "help" template (macros/start_hilfe.html). The user manual would benefit from the flask babel translation mechanism and the bulma css style we use for the rest of the web page.
For now it is only in German, simply because I feel more comfortable writing in German. As soon as the text is more or less stable we could translate it to English.  
I could finish a first draft of the text in the upcoming days. Before that I wanted to know what you think about the concept. 
> User manual

- arbeitszeit/injector.py
- tests/datetime_service.py
- tests/text_renderer.py
- tests/use_cases/dependency_injection.py
- tests/use_cases/repositories.py
This is a small maintenance patch that adds some type signatures with functions that didn't have any.
> Add some type signatures where they were lacking

- docs/development_guide.rst
This change replaces the out-of-date docs from the development guide regarding DB interaction with info on our current approach.
Plan-ID: b0aa02ca-667a-4028-998c-834f3186b418
> Replace out-of-date documentation on DB interface with current info

- constraints.txt
- flake.lock
> Update nix flake inputs and constraints.txt

- tests/data_generators.py
MemberGenerator.create_member was changed to not accept the confirmed_on argument anymore. This change was done since this feature cannot be supported with a monotonic flow of time (meaning that the hands of the clock only move forwards). Users that require to set a specific confirmed_on timestamp in test cases should instead use the `FakeDatetimeService` to manipulate the clock
(`freeze_time(timestamp)`, `advance_time(timedelta)`).
> tests: MemberGenerator.create_member does not accept confirmed_on

- constraints.txt
- flake.lock
> Update development dependencies

- .gitignore
- flake.nix
This small change accommodates work performed on Mac OS machines.
> Changes to top-level Flake file and ignoring Vim swap files.

- arbeitszeit_development/update_dependencies.py
- arbeitszeit_development/update_python_packages.py
- nix/pythonPackages/is-safe-url.json
- nix/pythonPackages/is_safe_url.nix
> Include is_safe_url python package in dependency update program

- arbeitszeit/price_calculator.py
We removed an obsolete class `PriceComponents` and improved the naming of variables slightly.  Also the explicit construction of AssertionError was removed in favor of the `assert` statement.
> Refactored arbeitszeit.price_calculator

- flake.lock
Run `python -m arbeitszeit_development.update_dependencies` to update the development dependencies.
*No accounting needed*
> Update development and python dependencies

- arbeitszeit_flask/templates/macros/draft_form.html
This PR contains changes related to https://github.com/arbeitszeit/arbeitszeitapp/issues/626. I swapped two HTML blocks in the company new plan form.
> Issue-626: Swap block order in plan form

- arbeitszeit_flask/templates/member/consumptions.html
> Show the value in the Amount column for a member's private consumption.

- arbeitszeit_flask/translations/de/LC_MESSAGES/messages.po
- arbeitszeit_flask/translations/en/LC_MESSAGES/messages.po
- arbeitszeit_flask/translations/messages.pot
**Automatically update pot and po files** 
The newly generated strings have not been translated yet.
**Translate several strings from EN to DE**
Plan: fd00d0bb-0ea3-4338-b097-dfa605278f1c (2x)
> Translate from EN to DE

- README.rst
- tests/use_cases/test_query_plans.py
fixes https://github.com/arbeitszeit/arbeitszeitapp/issues/821
> Reestablish nix path after mac os upgrade

- arbeitszeit/email_notifications.py
- arbeitszeit/use_cases/change_user_password.py
- arbeitszeit/use_cases/request_user_password_reset.py
- tests/use_cases/repositories.py
- tests/use_cases/test_change_user_password.py
- tests/use_cases/test_request_user_password_reset.py
plan: fe0d3b00-3fee-47d5-9f46-a1722b4bf873 5x
> Add request user passwort reset and change user password use cases

- tests/use_cases/test_show_r_account_details.py
Refactor and expand show r account use case tests.
Plan: b05bef9c-4dbf-4cd1-9e99-59219dfa9c4b (1x)
> Refactor show r account details tests

- arbeitszeit_flask/translations/de/LC_MESSAGES/messages.po
- arbeitszeit_flask/translations/en/LC_MESSAGES/messages.po
- arbeitszeit_flask/translations/es/LC_MESSAGES/messages.po
- arbeitszeit_flask/translations/messages.pot
Parse our code for translatable strings and translate new strings to DE and ES.
Plan: 371825c0-3112-47cd-9cb0-fea799fad3ee
> Translate latest strings to EN and ES

- arbeitszeit/use_cases/get_member_dashboard.py
- arbeitszeit_flask/member/routes.py
- arbeitszeit_web/www/presenters/get_member_dashboard_presenter.py
- tests/use_cases/balance_checker.py
- tests/use_cases/test_get_member_dashboard.py
- tests/use_cases/test_register_member.py
- tests/www/presenters/test_get_member_dashboard_presenter.py
The GetMemberDashboardUseCase and its use case tests did not adhere to our development guide and have been refactored accordingly.
Plan: 8ec03a5b-3dbe-465d-a533-4b3bfe16121b (1x)
> Refactor GetMemberDashboardUseCase and tests

- tests/api/integration/base_test_case.py
- tests/api/integration/test_list_active_plans_api.py
- Added a new enum class `LogInUser` to base_test_case.py to represent different types of users.
- Added the `login_user` method in base_test_case.py to handle different types of users.
- Updated the test cases in test_list_active_plans_api.py to use the `LogInUser` enum for authentication.
- Parametrized tests for improved readability in test_list_active_plans_api.py
Plan: 8ec03a5b-3dbe-465d-a533-4b3bfe16121b
> Refactor api base_test_case.py and test_list_active_plans_api.py

- arbeitszeit_flask/templates/user/query_plans.html
- arbeitszeit_flask/views/query_plans.py
- arbeitszeit_web/www/controllers/query_plans_controller.py
- arbeitszeit_web/www/presenters/query_plans_presenter.py
- tests/www/controllers/test_query_plans_controller.py
- tests/www/presenters/test_query_plans_presenter.py
**Refactor query plans controller and presenter** 
Controller and presenter have been separated and moved into their corresponding controller/presenter folders.
**Show number of results on query plans page**
fixes #1082
Plan: 8ec03a5b-3dbe-465d-a533-4b3bfe16121b (2x)
> Show number of results on query plans page

- arbeitszeit/email_notifications.py
- arbeitszeit/use_cases/remove_worker_from_company.py
- tests/use_cases/repositories.py
- tests/use_cases/test_remove_worker_from_company.py
Introduce business logic to remove worker from company.
see #1092.
Plan: 8ec03a5b-3dbe-465d-a533-4b3bfe16121b (3x)
> RemoveWorkerFromCompanyUseCase

- arbeitszeit_web/email/email_sender.py
- arbeitszeit_web/email/notify_worker_about_removal_from_company_presenter.py
- tests/email_presenters/test_notify_worker_about_removal_from_company_presenter.py
The implementation uses our usual email interface.
See #1092
> Create email to worker about removal from company

- arbeitszeit_flask/__init__.py
- arbeitszeit_flask/configuration_base.py
- docs/development_guide.rst
This commit allows admins/users of the application to provide a custom alembic config file for their installation of the arbeitszeitapp.
> Allow admins to configure alembic.ini config file path

- arbeitszeit_flask/accountant/blueprint.py
- arbeitszeit_flask/company/blueprint.py
- arbeitszeit_flask/user/blueprint.py
- arbeitszeit_web/www/authentication.py
- tests/flask_integration/flask.py
- tests/flask_integration/test_authentification.py
- tests/flask_integration/test_company_dashboard_view.py
- tests/flask_integration/test_private_consumptions_view.py
- tests/flask_integration/test_url_index.py
**Minor refactoring around authentification**
**Improve authentification of accountant** 
- display messages for unauthenticated users or users with wrong login
- set next url in session cookie for unauthenticated users
**Improve authentication in "user" route** 
Display warning to log in for unauthenticated users.
**Add integration tests for authentication**
> Improvements around authentication

- arbeitszeit_flask/auth/routes.py
- arbeitszeit_flask/templates/macros/anonymous_navigation.html
> Delete unnecessary 'auth.zurueck' route.

- arbeitszeit_flask/templates/macros/transactions.html
- arbeitszeit_web/www/presenters/get_member_account_presenter.py
- tests/www/presenters/test_get_member_account_presenter.py
The purpose was just the string "Lohn". Fixes #1165
> Don't show purpose of wage transaction

- arbeitszeit_flask/templates/company/create_cooperation.html
- arbeitszeit_flask/templates/company/my_consumptions.html
- arbeitszeit_flask/templates/company/my_plans.html
- arbeitszeit_flask/templates/company/request_cooperation.html
- arbeitszeit_flask/templates/member/consumptions.html
- arbeitszeit_flask/templates/user/company_account_a.html
- arbeitszeit_flask/templates/user/company_account_p.html
- arbeitszeit_flask/templates/user/company_account_prd.html
- arbeitszeit_flask/templates/user/company_account_r.html
- arbeitszeit_flask/templates/user/company_accounts.html
- arbeitszeit_flask/templates/user/get_company_transactions.html
- arbeitszeit_flask/translations/de/LC_MESSAGES/messages.po
- arbeitszeit_flask/translations/en/LC_MESSAGES/messages.po
- arbeitszeit_flask/translations/es/LC_MESSAGES/messages.po
- arbeitszeit_flask/translations/messages.pot
- Delete superfluous `</i>` html elements
- Add info texts and tooltips on "my plans" page
- Translation: Update pot and po files
- German translation of latest strings
- Spanish translation of latest strings
> Add info on my plans and translate strings

- README.rst
- docs/how_to_contribute.rst
- docs/index.rst
- Change ordering of doc pages, from abstract to concrete
- create a separate page for "how to contribute"
- Enhance README.md
> Changes to dev docs

- arbeitszeit/records.py
- arbeitszeit/repositories.py
- arbeitszeit/use_cases/create_cooperation.py
- arbeitszeit_flask/database/models.py
- arbeitszeit_flask/database/repositories.py
- arbeitszeit_flask/migrations/versions/eb928efc4311_add_psf_account_and_cooperation_account.py
- docs/concepts.rst
- tests/flask_integration/database_gateway_impl/test_account_result.py
- tests/flask_integration/database_gateway_impl/test_cooperation_result.py
- tests/flask_integration/flask.py
- tests/use_cases/repositories.py
- Clean test db in teardown: Drop alembic_version table and types
- Add PSF and coop accounts to db models
- Add PSF and coop accounts to records and repo methods
- Add coop account to dev docs
fixes #1189
> Add PSF and coop accounts

- docs/development_guide.rst
- Delete section on http from development guide 
The content of this section is mostly of general knowledge, not specific to our application.
- Add section on transfers to development guide 
This section explains how we create transfer records.
> Changes to developer guide

- tests/flask_integration/dev_cli.py
- tests/flask_integration/test_data_generation_cli.py
Add new commands and options, add tests.
> Enhance test data generator CLI

- arbeitszeit_flask/templates/company/dashboard.html
- arbeitszeit_flask/templates/member/dashboard.html
- arbeitszeit_flask/templates/user/list_transfers.html
- arbeitszeit_flask/user/routes.py
- arbeitszeit_flask/views/list_transfers.py
- arbeitszeit_web/www/controllers/list_transfers_controller.py
- arbeitszeit_web/www/presenters/list_transfers_presenter.py
- tests/flask_integration/test_list_transfers_view.py
- tests/www/controllers/test_list_transfers_controller.py
- tests/www/presenters/test_list_transfers_presenter.py
> Implement adapter and flask layer of ListTransfersUseCase

- arbeitszeit_flask/translations/de/LC_MESSAGES/messages.po
- arbeitszeit_flask/translations/en/LC_MESSAGES/messages.po
- arbeitszeit_flask/translations/es/LC_MESSAGES/messages.po
- arbeitszeit_flask/translations/messages.pot
- arbeitszeit_web/www/presenters/list_transfers_presenter.py
- Extract and update translatable strings
- Add missing translations to ES and DE
> Translations
