ida-arbeitszeit/arbeitszeitapp

arbeitszeit_flask/company/blueprint.py, arbeitszeit_flask/member/blueprint.py, arbeitszeit_flask/types.py, arbeitszeit_flask/views/end_cooperation_view.py
Before this change it was difficult to annotate view functions that would return a redirect. This issue came from an oversight in the type hints for `flask` itself. The `flask.redirect` method does not return a `flask.Response` object but instead an object of type `werkzeug.wrappers.response.Response`.
This issue was "resolved" by creating a type alias for `Union[flask.Response, werkzeug.wrappers.response.Response]`. Programmers are encouraged to uses this new type alias when annotating functions.
=> Create alias for response union type

.github/workflows/python-app.yml, run-checks
Before this change the CI pipeline steps using the `nix` build tool were running the unittests twice: Once as part of `nix build` and then again as part of `./run-checks`. To avoid this I introduced an optional argument to the `./run-checks` program that disables unittests.
=> Avoid running unittests in CI twice

requirements.txt
Cryptography is not required by us. This is why I removed it from our requirements file.
No payment needed.
=> Remove cryptography from dependecies

requirements.txt
pygments is not required by us. This is why I removed it from requirements.txt
No payment required.
=> Remove pygments from requirements

arbeitszeit/use_cases/get_plan_summary_company.py, arbeitszeit_flask/company/routes.py, arbeitszeit_flask/templates/company/plan_summary.html, arbeitszeit_web/get_plan_summary_company.py, tests/presenters/test_get_plan_summary_company_presenter.py, tests/use_cases/test_get_plan_summary_company.py
fixes #298
After this PR companies can only see the "action section" (i.e. change visibility button and end cooperation button) of their own plan's summary pages. Consequently, they won't be able to see the action sections of other company's plans anymore.
=> show action section only if current user is planner

arbeitszeit/use_cases/__init__.py, arbeitszeit/use_cases/show_prd_account_details.py, arbeitszeit_flask/company/routes.py, arbeitszeit_flask/dependency_injection/__init__.py, arbeitszeit_flask/templates/company/account_prd.html, arbeitszeit_flask/templates/company/my_accounts.html, arbeitszeit_web/presenters/show_prd_account_details_presenter.py, tests/presenters/test_show_prd_account_details_presenter.py, tests/use_cases/test_show_prd_account_details.py
In the overview page of company's accounts, links to the detail pages of p, r and a accounts have already been implemented, but the prd-account was still missing. 
This PR is resolving this by adding the missing detail page for the product account.
=> Add product (prd) account details

arbeitszeit_flask/translations/de/LC_MESSAGES/messages.po, arbeitszeit_flask/translations/en/LC_MESSAGES/messages.po, arbeitszeit_web/pay_consumer_product.py, tests/controllers/test_pay_consumer_product_controller.py, tests/presenters/test_pay_consumer_product_presenter.py
fixes #319
What this PR does:
1) prevent payment of negative amounts of consumer products
2) make arbeitszeit_web/pay_consumer_product.py translatable
3) translate it to German
My Plan-ID: e8e5c56f-9e2d-497d-a896-a26bc41e1c16
=> Prevent payment of negative amounts of consumer products

arbeitszeit/entities.py, arbeitszeit/repositories.py, arbeitszeit/use_cases/seek_approval.py, arbeitszeit/use_cases/show_my_plans.py, arbeitszeit_flask/company/routes.py, arbeitszeit_flask/database/repositories.py, arbeitszeit_flask/models.py, arbeitszeit_flask/templates/company/create_draft.html, arbeitszeit_flask/templates/company/my_plans.html, arbeitszeit_web/get_prefilled_draft_data.py, arbeitszeit_web/show_my_plans.py, migrations/versions/bc2747c3b268_delete_column_renewed_from_table_plan.py, tests/data_generators.py, tests/presenters/test_get_prefilled_draft_data_presenter.py, tests/presenters/test_show_my_plans_presenter.py, tests/use_cases/repositories.py, tests/use_cases/test_seek_approval.py
I think that the "create plan" procedure is unnecessarily complicated - especially the "plan renewal" part of it. "Plan renewal" should simply mean to take the plan info of an expired plan and copy it into a new plan draft. 
But right now the old plan is marked as "renewed" as well. This is unnecessarily complex: In my opinion, neither a future plan approval workflow nor accumulation control workflow will need the category of a "renewed plan". *) 
That's why I propose in this PR to delete the "Plan.renewed" attribute. "Renewing" a plan still is possible in the simpler meaning of copying the plan content to a new draft. Do you agree?
In an upcoming PR i would then refactor some of the parts of the "create plan" procedure. 
My Plan-ID: e8e5c56f-9e2d-497d-a896-a26bc41e1c16
------
*) The …
=> Simplify plan renewal

CONDUCT.rst
This implements the change that we discussed recently where we wanted to have a dedicated email address for community outreach. The email address is currently registered under @seppeljordan 
=> Put correct contact email into CoC

arbeitszeit/use_cases/create_plan_draft.py, arbeitszeit_flask/templates/company/create_draft.html, arbeitszeit_web/get_prefilled_draft_data.py
fixes #321
This PR prevents that companies specify negative plan costs. It does this 1) in the html ``input`` element and 2) by assertions in the controller.
I refrained from refactoring the controller any further because I plan to propose some changes related to plan creation backend soon.
My Plan-ID: e8e5c56f-9e2d-497d-a896-a26bc41e1c16
=> Prevent-negative-plan-costs

arbeitszeit/use_cases/query_plans.py, arbeitszeit_flask/dependency_injection/__init__.py, arbeitszeit_flask/templates/macros.html, arbeitszeit_flask/templates/macros/company_summary.html, arbeitszeit_web/get_company_summary.py, arbeitszeit_web/query_companies.py, arbeitszeit_web/query_plans.py, tests/presenters/test_get_company_summary_presenter.py, tests/presenters/test_query_companies_presenter.py, tests/presenters/test_query_plans_presenter.py, tests/use_cases/test_query_plans.py
fixes #281 
As described in issue #281, I added internal links to three views, using the UrlIndex system:
- company_summary
- query_companies
- query_plans
EDIT: In my opinion this should fix issue 281. I would like to have some internal links in the account views, but that is a more complicated thing to do and should be a different issue/PR.
=> Adding more internal links

cron_job_heroku.sh
Since around two weeks the hourly cron job on prod server did not run.
Heroku logs did show:
```
2022-03-28T19:01:02.730212+00:00 heroku[scheduler.4154]: State changed from starting to up
2022-03-28T19:01:04.420068+00:00 app[scheduler.4154]: Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.
``` 
It has been fixed in this PR (and already pushed to heroku) by defining the FLASK_APP environment variable in the cron job script.  
Luckily the `flask payout` command is intelligent enough to pay out missed payouts from the past as soon as it runs again.
Plan-ID: e8e5c56f-9e2d-497d-a896-a26bc41e1c16
=> adding FLASK_APP envvar to cron job script

README.rst, arbeitszeit_flask/__init__.py, arbeitszeit_flask/commands.py, startapp_heroku.sh, update-translations
This PR proposes some changes to the translation procedure:
- It deactivates babel's fuzzy matching (babel was trying to find translations of similar strings in our catalog). That was not working well.
- All flask-related translation files are now in the `arbeitszeit_flask` module, not on top level of the application
- There are now simple flask custom commands to execute the rather lenghty babel commands
- README has been adapted
Plan: e8e5c56f-9e2d-497d-a896-a26bc41e1c16
=> Changes to translation procedure

tests/presenters/dependency_injection.py, tests/presenters/test_list_messages_presenter.py, tests/presenters/test_list_plans_presenter.py, tests/presenters/test_list_workers_presenter.py, tests/presenters/test_pay_consumer_product_presenter.py, tests/presenters/test_pay_means_of_production_presenter.py, tests/presenters/test_plan_summary_service.py, tests/presenters/test_query_companies_presenter.py, tests/presenters/test_query_plans_presenter.py, tests/presenters/test_read_message_presenter.py, tests/presenters/test_request_cooperation_presenter.py, tests/presenters/url_index.py, tests/presenters/user_action_resolver.py
This is a continuation of the ongoing refactoring effort. Mainly some more presenter tests were refactored to use dependency injection in their object construction. The long term goal here is to reduce coupling between the test cases and the object construction for classes that are not under test.
=> Refactor presenter tests to utilize dependency injection

arbeitszeit_flask/auth/routes.py, arbeitszeit_flask/dependency_injection/__init__.py, arbeitszeit_flask/dependency_injection/views.py, arbeitszeit_flask/flask_session.py, arbeitszeit_flask/forms.py, arbeitszeit_flask/views/signup_member_view.py, arbeitszeit_web/presenters/register_member_presenter.py, arbeitszeit_web/register_member.py, arbeitszeit_web/session.py, tests/controllers/test_register_member_controller.py, tests/presenters/dependency_injection.py, tests/presenters/test_register_member_presenter.py, tests/session.py
This PR refactors the route `/member/signup`.
This presenter is a little different from other presenters that we already implement. Its responsibility is not only to render html to the user but also to sign the user in when the registration attempt was successful. I extended the concept of a `Session` to accommodate the change. Furthermore the error message that appears when an email is already registered is now translatable.
This view is functionally identical to the code that was previously in the route. The newly implemented presenter replaced the code that handled successful form submissions.
I'm looking forward to feedback on this change since I would like to adopt this approach for the route `/company/register` and later `/accountant/register`.
Plan-ID: …
=> Refactor /member/signup

arbeitszeit_flask/auth/routes.py, arbeitszeit_flask/company/blueprint.py, arbeitszeit_flask/dependency_injection/__init__.py, arbeitszeit_flask/dependency_injection/views.py, arbeitszeit_flask/flask_session.py, arbeitszeit_flask/views/signup_member_view.py, arbeitszeit_web/session.py, tests/session.py
This PR refactors the auth routes with respect to logging in and logging out.  All login related functions are now handled by `FlaskSession`. Unfortunately I was not able to remove some references to `session["user_type"]` from the rest of the code (which would be desirable IMO).
=> Let FlaskSession handle login and logout

MANIFEST.in, setup.cfg
This PR is about packaging. With the change proposed by this PR the templates used by `arbeitszeitapp` are also included in source and binary distributions of the app.
=> Include templates in package data

arbeitszeit_web/get_member_profile_info.py, arbeitszeit_web/get_statistics.py, tests/presenters/dependency_injection.py, tests/presenters/test_colors.py
fixes #309
This PR fixes two different pytest warnings: 
- warnings about the usage of ngettext in combination with Decimal
- a warning that was raised because of the naming of `TestColors`
=> Fix-pytest-warnings

arbeitszeit_flask/company/routes.py, arbeitszeit_flask/dependency_injection/__init__.py, arbeitszeit_flask/dependency_injection/views.py, arbeitszeit_flask/forms.py, arbeitszeit_flask/templates/company/create_cooperation.html, arbeitszeit_flask/templates/company/dashboard.html, arbeitszeit_flask/templates/company/my_cooperations.html, arbeitszeit_flask/templates/company/plan_summary.html, arbeitszeit_flask/translations/de/LC_MESSAGES/messages.po, arbeitszeit_flask/url_index.py, arbeitszeit_flask/views/create_cooperation_view.py, arbeitszeit_web/get_plan_summary_company.py, arbeitszeit_web/get_plan_summary_member.py, arbeitszeit_web/plan_summary_service.py, arbeitszeit_web/url_index.py, tests/flask_integration/test_create_cooperation_view.py, tests/flask_integration/test_url_index.py, tests/presenters/dependency_injection.py, tests/presenters/test_get_plan_summary_company_presenter.py, tests/presenters/test_plan_summary_service.py, tests/presenters/url_index.py
This PR aims for a (hopefully) more intuitive cooperation interface. 
- Requesting a cooperation is now found in "plan summary" page
- Creating a cooperation is now found in "my cooperations" 
- It introduces a tile layout for the plan summary action section
It also reduces items on the dashboard, making it less overwhelming and hiding away "advanced" functions.
- Delete request cooperation from dashboard
- Delete create cooperation from dashboard
P.S.: I deleted a user facing sentence in create_cooperation.html, which seemed to me an unnecessary detail for the normal user. I can change it again.
=> Changes to cooperation creation and request

arbeitszeit_flask/templates/company/transfer_to_company.html, arbeitszeit_flask/templates/company/transfer_to_worker.html, arbeitszeit_flask/templates/member/pay_consumer_product.html
Our three payment/transfer forms (pay means of production, pay consumer product, transfer work certificates) are not mobile responsive: They exceed the screen horizontally. 
This PR fixes this. 
=> make transfer forms responsive

arbeitszeit/plan_summary.py, arbeitszeit/use_cases/__init__.py, arbeitszeit/use_cases/get_plan_summary_company.py, arbeitszeit/use_cases/get_plan_summary_member.py, arbeitszeit_flask/company/routes.py, arbeitszeit_flask/member/routes.py, arbeitszeit_flask/templates/company/plan_summary.html, arbeitszeit_flask/templates/macros/plan_summary.html, arbeitszeit_flask/views/create_draft_view.py, arbeitszeit_web/get_plan_summary_company.py, arbeitszeit_web/get_plan_summary_member.py, arbeitszeit_web/get_prefilled_draft_data.py, arbeitszeit_web/plan_summary_service.py, tests/presenters/test_get_plan_summary_company_presenter.py, tests/presenters/test_get_prefilled_draft_data_presenter.py, tests/presenters/test_plan_summary_service.py, tests/use_cases/test_get_plan_summary_company.py, tests/use_cases/test_get_plan_summary_member.py
This PR changes the plan summary page by
1) applying the "tile" layout
2) adding a timeframe information to the plan summary page (how many days of the planning timeframe have passed?)
3) some refactoring, cleaning up and renaming on the back end side
The web design/style can of course be discussed. I think it's less intimitating than simple table rows with data.
=> Reworking plan summary page

arbeitszeit_flask/dependency_injection/__init__.py, arbeitszeit_flask/templates/company/my_plans.html, arbeitszeit_web/show_my_plans.py, tests/presenters/dependency_injection.py, tests/presenters/test_show_my_plans_presenter.py
This PR changes the front end design of the "my plans" overview, making it responsive, very similar to "all plans" overview that has been redesigned already. 
=> Reworking "my plans" overview

arbeitszeit_flask/templates/company/my_purchases.html
Update jinja2 template to round `price_per_unit` and `price_total` to 1 decimal place.
https://github.com/arbeitszeit/arbeitszeitapp/issues/428
=> fix(#428): ROUND PAST PRICE OF COMPANIES

arbeitszeit/plan_summary.py, arbeitszeit_flask/dependency_injection/__init__.py, arbeitszeit_flask/templates/macros/plan_summary.html, arbeitszeit_web/plan_summary_service.py, tests/presenters/dependency_injection.py, tests/presenters/test_get_plan_summary_company_presenter.py, tests/presenters/test_get_prefilled_draft_data_presenter.py, tests/presenters/test_plan_summary_service.py, tests/services/test_plan_summary_service.py, tests/use_cases/test_get_plan_summary_company.py, tests/use_cases/test_get_plan_summary_member.py
This PR adds some more essential information to the plan summary page, namely plan creation, plan approval and plan expiration dates. 
Also some refactoring of the plan summary use case tests have been made which reduced code duplication.
Plan-ID: 26f2e3f6-233a-4ef1-a1a0-39c5d411b38c
=> Add more time information to plan summary

arbeitszeit/use_cases/query_plans.py, arbeitszeit_flask/forms.py, arbeitszeit_flask/templates/macros/query_plans.html, arbeitszeit_web/query_plans.py, tests/controllers/test_query_plans_controller.py, tests/flask_integration/test_query_plan_view.py, tests/presenters/test_query_plans_presenter.py, tests/use_cases/test_query_plans.py
fixes #418
This PR enables sorting when querying all active plans. The user can sort the results by activation date, company name or price. By default plans are sorted by activation date (newest plans first).
This PR should close #418. It is still an open question though if we need product categories. 
=> Enabling sorting of results of QueryPlans

arbeitszeit_flask/dependency_injection/presenters.py, arbeitszeit_flask/templates/company/list_all_transactions.html, arbeitszeit_flask/templates/macros/company_summary.html, arbeitszeit_web/get_company_summary.py, arbeitszeit_web/get_company_transactions.py, tests/presenters/dependency_injection.py, tests/presenters/test_get_company_summary_presenter.py, tests/presenters/test_get_company_transactions.py, tests/presenters/test_get_member_dashboard_presenter.py
This PR does a bit of refactoring, moving datetime formatting from two html templates into corresponding presenters (`GetCompanySummarySuccessPresenter` and `GetCompanyTransactionsPresenter`). I also adjusted tests. 
P.S: I noticed that we are using unittest.subTest(), but pytest cannot take advantage of them. At some point we could think about using a pytest plugin (https://pypi.org/project/pytest-subtests/). 
Plan-ID: 26f2e3f6-233a-4ef1-a1a0-39c5d411b38c
=> Move datetime formatting into presenters

arbeitszeit_flask/templates/company/account_a.html, arbeitszeit_flask/templates/company/account_p.html, arbeitszeit_flask/templates/company/account_prd.html, arbeitszeit_flask/templates/company/account_r.html, arbeitszeit_flask/templates/company/draft_list.html, arbeitszeit_flask/templates/company/invite_worker_to_company.html, arbeitszeit_flask/templates/company/list_all_cooperations.html, arbeitszeit_flask/templates/company/list_all_transactions.html, arbeitszeit_flask/templates/company/my_accounts.html, arbeitszeit_flask/templates/company/my_cooperations.html, arbeitszeit_flask/templates/company/my_plans.html, arbeitszeit_flask/templates/company/my_purchases.html, arbeitszeit_flask/templates/macros/company_summary.html, arbeitszeit_flask/templates/macros/coop_summary.html, arbeitszeit_flask/templates/macros/query_companies.html, arbeitszeit_flask/templates/member/my_account.html, arbeitszeit_flask/templates/member/my_purchases.html
There are some formatting issues with the thml tables in the current code (e.g. table content is centered, while headers aren't). 
I applied now the same bulma based formatting to all tables: `<table class="table has-text-left mx-auto">` 
This garantees that text is by default aligned to the left, which makes it easy to read, while the table takes only as much space as it needs.
Plan-ID: ed6eb89f-0633-4544-9ddc-94466b7d5e82
=> Reformat html tables

requirements.txt
After #444 there is a small problem with deploying on Heroku: Apparently Heroku does not accept our `-c constraints.txt` command in our `requirements.txt` file, so our deployment failed. 
Heroku writes: 
```
If you would like to utilize multiple requirements files in your codebase, you can include the contents of another requirements file with pip:
`-r ./path/to/prod-requirements.txt`
```
https://devcenter.heroku.com/articles/python-pip
Changing our `-c constraints.txt` command to `-r constraints.txt` did the job. If there is not a specific reason to use `-c` i'd suggest with this PR to apply this change in our code.
=> Change command in requirements.txt from -c to -r

arbeitszeit/use_cases/get_coop_summary.py, arbeitszeit_flask/dependency_injection/presenters.py, arbeitszeit_flask/templates/macros/coop_summary.html, arbeitszeit_web/get_coop_summary.py, tests/presenters/dependency_injection.py, tests/presenters/test_get_coop_summary_presenter.py, tests/use_cases/test_get_coop_summary.py
fixes #481
show name and link of coordinator in coop summary (see issue #481).
Still using here the old style of dependency injection to prevent merge conflicts.
=> show name and link of coordinator in coop summary

arbeitszeit_flask/dependency_injection/__init__.py, arbeitszeit_flask/dependency_injection/presenters.py, arbeitszeit_flask/dependency_injection/views.py, arbeitszeit_flask/forms.py, arbeitszeit_flask/templates/company/plan_summary.html, arbeitszeit_flask/templates/company/transfer_to_company.html, arbeitszeit_flask/url_index.py, arbeitszeit_flask/views/pay_means_of_production.py, arbeitszeit_web/controllers/pay_means_of_production_controller.py, arbeitszeit_web/forms.py, arbeitszeit_web/get_coop_summary.py, arbeitszeit_web/get_plan_summary_company.py, arbeitszeit_web/pay_means_of_production.py, arbeitszeit_web/url_index.py, tests/controllers/dependency_injection.py, tests/controllers/test_pay_means_of_production_controller.py, tests/dependency_injection.py, tests/flask_integration/test_url_index.py, tests/forms.py, tests/presenters/dependency_injection.py, tests/presenters/test_get_coop_summary_presenter.py, tests/presenters/test_get_plan_summary_company_presenter.py, tests/presenters/test_pay_means_of_production_presenter.py, tests/presenters/url_index.py
fixes #413
This PR adds a link to the plan summary pages, as seen by companies (if they are not the planner of the plan), to pay the product more easily. When they click the link, they get forwarded to the payment page, with the UUID of the plan already filled in.
The PR got quite big because I had to touch the plan summary page as well as the pay means of production page and implement the new url index, dependecy injection and form approach.
Plan-ID: ed6eb89f-0633-4544-9ddc-94466b7d5e82
=> Make paying means of production from plan possible

arbeitszeit/transactions.py, arbeitszeit/use_cases/show_prd_account_details.py, flake.nix, tests/presenters/test_show_prd_account_details_presenter.py, tests/use_cases/test_show_prd_account_details.py
This PR is a first step to solve that companies cannot see who paid products in their PRD-account (see issue #435). 
To make it possibe, a `buyer` field is added to the Response object of the `ShowPRDAccountDetailsUseCase`.
This is so far only the Use Case implementation. If approved, a second PR will deal with the presenter level. 
Plan ID: ecdb2bb1-6690-4a6e-a8a5-d08e26ac1afd
=> show buyer in company's prd account (use case)

arbeitszeit_flask/templates/company/account_prd.html, arbeitszeit_web/presenters/show_prd_account_details_presenter.py, tests/presenters/test_show_prd_account_details_presenter.py
fixes #435
This PR adds a new column in the company's prd account overview, where the buyer of the product is shown. The buyer of a product is currently only represented by its name and an icon that shows if the buyer is a worker or a company. 
Later we can add more information, when needed, e.g. an ID or a link to the company summary page. 
In case the transaction in a given row is not a sale but a expected sales debit, the field stays empty.  
Plan-ID: ecdb2bb1-6690-4a6e-a8a5-d08e26ac1afd
=> Show buyer in prd account presenter

arbeitszeit_flask/templates/company/account_a.html, arbeitszeit_flask/templates/company/account_p.html, arbeitszeit_flask/templates/company/account_r.html, arbeitszeit_flask/templates/macros/transactions.html, arbeitszeit_flask/translations/de/LC_MESSAGES/messages.po
This PR makes the list of transactions of accounts p, r and a mobile responsive. Account prd will follow after merge of PR #505.
Because the transactions items do all look the same in these 3 acccounts, I created a jinja macro `basic_transaction(date, type, purpose, volume)`.
Plan-ID: ecdb2bb1-6690-4a6e-a8a5-d08e26ac1afd
=> change transaction appearance for accounts p, r, a

arbeitszeit_flask/templates/company/plan_summary.html, arbeitszeit_web/get_plan_summary_company.py, tests/presenters/test_get_plan_summary_company_presenter.py
fixes #504
This PR hides the "action" section of company's own plan, if the plan is inactive. 
The idea is that neither changing availability nor joining a cooperation makes sense for an expired plan.
(Currently, "inactive" means "expired". In the future, this assumption may not hold and we may have to change the bahaviour accordingly.)
=> Don't show "actions" in plan summary of inactive plans

arbeitszeit_flask/models.py, arbeitszeit_flask/static/main.css, arbeitszeit_flask/templates/base_company.html, arbeitszeit_flask/templates/base_member.html
This PR proposes to add to the navbar an icon ("user" or "industry") depending on if the currently logged-in user role is member or company. It also adds the name of the user to the navbar.
The intention of this change is to make it clearer to users, which account they are logged in with. 
It also fixes a small bug in the burger menu on small screens (buttons were arranged horizontally instead of vertically).
Plan ID: ecdb2bb1-6690-4a6e-a8a5-d08e26ac1afd
=> Show name and user type in navbar

README.rst, tests/presenters/test_get_member_dashboard_presenter.py
For the translation setup there was a step in the README missing (the part with `extract_messages`)
Moreover there was a wrong string interpolation (using translator + f-string) in a test function which prevented the extract_messages command to succeed.
(I'll get a merge commit with #538, but that's ok)
=> Translation setup: adapt README, fix bug

README.rst, arbeitszeit_flask/__init__.py, arbeitszeit_flask/configuration_base.py, arbeitszeit_flask/development_settings.py, arbeitszeit_flask/production_settings.py, tests/flask_integration/dependency_injection.py
FLASK_ENV and the ENV attribute are deprecated since flask 2.2 and won't be used from flask 2.3. I adapted our code to use FLASK_DEBUG.
https://flask.palletsprojects.com/en/2.2.x/config/#ENV
=> Use FLASK_DEBUG instead of FLASK_ENV

tests/migration/sqlite_test_settings.py, tests/migration/test_sqlite.py
This PR implements tests for the DB migrations. Currently only tests with the `sqlite` dialect are implemented.
=> Implement tests for db migrations with sqlite

README.rst, docs/index.rst
Just a small change to Readme:
- Add sub-section "description" to introduction
- shorten the "theory" part
=> README: Add sub-section "description" to introduction

arbeitszeit_flask/static/main.css, arbeitszeit_flask/templates/base_accountant.html, arbeitszeit_flask/templates/base_company.html, arbeitszeit_flask/templates/base_member.html, arbeitszeit_flask/templates/macros/show_notifications.html
This PR gives notifications a fixed position on top of the screen and makes them disappear after 5 seconds. 
This change has been made so that users can see notifications even when they get directed to the middle of a page. 
Plan-ID: b33932e9-567a-4712-a48c-3ef347ec561e
=> Notifications: Fixed position + disappearing

arbeitszeit/entities.py, arbeitszeit/repositories.py, arbeitszeit/use_cases/update_plans_and_payout.py, arbeitszeit_flask/database/repositories.py, arbeitszeit_flask/migrations/versions/5517f6309552_delete_plan_expiration_date.py, arbeitszeit_flask/models.py, tests/entities/test_plan.py, tests/use_cases/repositories.py, tests/use_cases/test_update_plans_and_payout.py
Until now, a plan's expiration date has been calculated in `update_plans_and_payout` Use Case and stored in the database afterwards.
I think expiration date can simply be calculated when needed in the business logic. I made it a property of `Plan` entity. 
Let me know what you think about this change.
Plan ID (please add me to the cooperation before paying): b33932e9-567a-4712-a48c-3ef347ec561e
=> Delete expiration_date from `Plan` db model

arbeitszeit/use_cases/update_plans_and_payout.py, arbeitszeit_flask/templates/accountant/plans-to-review-list.html, tests/services/test_payout_factor_service.py, tests/use_cases/test_update_plans_and_payout.py
I noticed the following problem: 1) change activation date in the database. 2) run `flask payout`. 3) the FIK does not take the new activation_date into account (only when you run it a second time)
The same problem occurs when a plan has recently expired.
The reason for this behaviour is that calculate_plan_expiration depends on payout_factor (in order to pay out overdue wages of expired plans) and is therefore run AFTER the calculation of the payout factor. We would have to run the use case twice to get the desired result.
Instead I propose to use the latest available payout factor from the repo to pay out overdue wages. In consequence we can run calculate_plan_expiration BEFORE calculate_payout_factor.
A problem arises when there has never been calculated a payout factor and overdue …
=> Bug fix in UpdatePlansAndPayout

arbeitszeit/use_cases/__init__.py, arbeitszeit/use_cases/get_plan_summary_accountant.py, arbeitszeit/use_cases/list_plans_with_pending_review.py, arbeitszeit_flask/accountant/blueprint.py, arbeitszeit_flask/accountant/routes.py, arbeitszeit_flask/dependency_injection/__init__.py, arbeitszeit_flask/member/routes.py, arbeitszeit_flask/template.py, arbeitszeit_flask/templates/accountant/404.html, arbeitszeit_flask/templates/accountant/company_summary.html, arbeitszeit_flask/templates/accountant/plan_summary.html, arbeitszeit_flask/templates/accountant/plans-to-review-list.html, arbeitszeit_flask/url_index.py, arbeitszeit_web/get_plan_summary_accountant.py, arbeitszeit_web/get_plan_summary_member.py, arbeitszeit_web/presenters/list_plans_with_pending_review_presenter.py, tests/flask_integration/test_get_company_summary.py, tests/flask_integration/test_get_plan_summary.py, tests/presenters/test_get_plan_summary_company_presenter.py, tests/presenters/test_get_plan_summary_member_presenter.py, tests/presenters/test_list_plans_with_pending_review_presenter.py, tests/use_cases/test_get_plan_summary_accountant.py, tests/use_cases/test_list_plans_with_pending_review.py
fixes #566 
Among other things I created two routes for accountants, `plan_summary` and `company_summary`.
I noticed there were no integration tests for the company_summary page.
I did not implement the links in the accountants list of unreviewed plans yet, to make this PR not too large.
Plan-ID: b33932e9-567a-4712-a48c-3ef347ec561e
=> Feature for list of unreviewed plans

.github/workflows/python-app.yml
I updated the versions of `actions/checkout`, `actions/setup-python`  and `cachix` in the CI workflow to suffice the deprecation warnings.
=> Update versions of actions if CI workflow

arbeitszeit/use_cases/list_inbound_coop_requests.py, arbeitszeit_flask/static/main.css, arbeitszeit_flask/templates/company/my_cooperations.html, arbeitszeit_web/show_my_cooperations.py, tests/presenters/test_show_my_cooperations_presenter.py, tests/use_cases/base_test_case.py, tests/use_cases/test_list_inbound_coop_requests.py
A step towards #415
Before adding a new section to `/company/my_cooperations` with a company's own cooperating plans in an upcoming PR, I firstly redesign the page here:
- make it mobile friendly (replace tables with bulma media object)
- add links to plan summaries and company summaries  
Plan-ID: b33932e9-567a-4712-a48c-3ef347ec561e
=> Redesign "my cooperations" page

arbeitszeit/entities.py, arbeitszeit/repositories.py, arbeitszeit/use_cases/update_plans_and_payout.py, arbeitszeit_flask/database/repositories.py, arbeitszeit_flask/dependency_injection/__init__.py, arbeitszeit_flask/migrations/versions/15d33dfe8ec7_.py, arbeitszeit_flask/models.py, tests/flask_integration/test_database_gateway_impl.py, tests/flask_integration/test_plan_repository.py, tests/use_cases/dependency_injection.py, tests/use_cases/repositories.py
Before this change we tracked the payout process of labour certificates by increasing a counter on the `Plan` model. This approach has several drawback:
1) It limits the amount of information we can track about the payout process of labour certificates. It would be hard to add additional information about the payout process since we would need to introduce additional fields to the `Plan` model. Let's say we wanted to track the FIK used when transferring labour certificates for each payout transaction. There would be no obvious way to do that currently.
2) It attaches information to a plan that are not related to the planning process itself but rather related to the payout process. The `Plan` model is unnecessarily rich in information that could be tracked separately.
For those reasons I …
=> Implement dedicated database record for tracking payout of labour certificates

arbeitszeit/entities.py, arbeitszeit/repositories.py, arbeitszeit/use_cases/get_statistics.py, arbeitszeit_flask/database/repositories.py, tests/flask_integration/test_plan_repository.py, tests/use_cases/repositories.py
This PR refactors the DB logic for retrieving global planning stats. The refactoring allows the collection of planning stats from any `PlanResult`. This makes it much easier to calculate planning statistics for any arbitrary set of plans, e.g. all public plans or all plans that are inside a cooperation and so on. Also less DB calls are made in the use case `GetStatistics`.
Plan-ID: b0aa02ca-667a-4028-998c-834f3186b418
=> Refactor planning stats

.github/workflows/python-app.yml
This should fix the current build errors. There is a regression in the installation script for nix 2.14. See https://github.com/NixOS/nixpkgs/pull/218858#issuecomment-1448758169 for further info.
=> Pin nix version in github pipeline to 2.13.3

arbeitszeit/repositories.py, arbeitszeit/use_cases/confirm_member.py, arbeitszeit_flask/database/repositories.py, tests/data_generators.py, tests/flask_integration/test_member_repository.py, tests/use_cases/repositories.py
The MemberResult.set_confirmation_timestamp method was moved to the newly introduced MemberUpdate interface. This was done to better follow the desired DB interface where update actions on selected rows can be aggregated before they are executed in one (or at least few) database operation.
Plan-ID: b0aa02ca-667a-4028-998c-834f3186b418
=> Refactor MemberRepository

arbeitszeit_flask/database/repositories.py, arbeitszeit_flask/flask_session.py, arbeitszeit_flask/models.py, pyproject.toml
Previously we made use of two sqlalchemy features that are now deprecated.
1) `Model.query.get(pk)` is now deprecated and was replaced with
```
orm = Model.query.filter(id=pk).first()
assert orm
```
2) `backref` and `relationship` cascades will be removed in sqlachemy 2.0. We implemented the recommended steps from their documentation at https://docs.sqlalchemy.org/en/14/errors.html#object-is-being-merged-into-a-session-along-the-backref-cascade
=> Stop using deprecated sqlalchemy features

arbeitszeit/repositories.py, arbeitszeit/use_cases/file_plan_with_accounting.py, arbeitszeit_flask/database/repositories.py, tests/flask_integration/test_plan_repository.py, tests/use_cases/repositories.py
Previously the DB interface for creating a plan accepted simply a PlanDraft.id to create a plan from the PlanDraft that the id referenced. With this change there is a dedicated methods for creating a plan independently from PlanDraft. The goal is to have a more flexible DB interface which is achieved by this change since now Plan records can be created without the need for a preexisting PlanDraft. Secondly the removes implicit logic from the DB. The previous approach relied on the DB implementation filling in the correct fields in the Plan from the PlanDraft that the Plan was created from. Now the business logic has complete control over what fields Plan records are created with. This means that we can test the usage of correct values once in the business logic instead of having to test …
=> Change DB interface for creating plans

arbeitszeit/plan_summary.py, arbeitszeit/repositories.py, arbeitszeit/use_cases/update_plans_and_payout.py, arbeitszeit_flask/database/repositories.py, arbeitszeit_flask/models.py, tests/flask_integration/test_plan_repository.py, tests/use_cases/repositories.py, tests/use_cases/test_update_plans_and_payout.py
With this change the labour certificate payout is changed such that certificates going to the A account of companies get transferred at the end of every full day the plan is active. Before this change the certificates got transferred at the start of each day a plan was active.
Also a bug was fixed were a company would get too many certificates if the payout use case was triggered exactly on the same time as the plan would expire.
Thirdly we introduced a method to filter plans from the DB such that only plans with pending payouts for labour certificates are selected.
Plan-ID: b0aa02ca-667a-4028-998c-834f3186b418
=> Changed labour certificate payout modalities

tests/data_generators.py
Before this change running `pytest
tests.use_cases.test_get_company_summary` resulted in errors. The reason for theses errors was that the attribute names of `PurchaseGenerator` clashed with module imports.
=> Fix error when running tests.use_cases.test_get_company_summary

.github/workflows/python-app.yml, constraints.txt, flake.lock
This patch updates the inputs to the nix flake in this repository. constraints.txt was also updated to reflect the changes in nixpkgs. Additionally the python version used in the test environment at GitHub was updated updated to python 3.10.10.
=> Update dependencies for development environment

arbeitszeit/entities.py, arbeitszeit/use_cases/delete_draft.py, arbeitszeit/use_cases/edit_draft.py, arbeitszeit/use_cases/file_plan_with_accounting.py, arbeitszeit/use_cases/get_draft_summary.py, arbeitszeit_flask/database/repositories.py, tests/data_generators.py, tests/flask_integration/test_plan_draft_repository.py, tests/use_cases/repositories.py, tests/use_cases/test_create_plan_draft.py, tests/use_cases/test_list_plans_with_pending_review.py
This patch changes the type of the `planner` field of the `PlanDraft` entity from being of type `Company` to `UUID`.  The UUID in this field is the id of the planning company. All code consuming the `PlanDraft` class was updated accordingly.
=> Change arbeitszeit.entities.PlanDraft.planner from Company to UUID

arbeitszeit/entities.py, arbeitszeit/repositories.py, arbeitszeit/transactions.py, arbeitszeit/use_cases/get_company_transactions.py, arbeitszeit/use_cases/get_member_account.py, arbeitszeit/use_cases/register_company/__init__.py, arbeitszeit/use_cases/register_member/__init__.py, arbeitszeit/use_cases/show_a_account_details.py, arbeitszeit/use_cases/show_p_account_details.py, arbeitszeit/use_cases/show_prd_account_details.py, arbeitszeit/use_cases/show_r_account_details.py, arbeitszeit_flask/database/repositories.py, arbeitszeit_flask/migrations/versions/35ec3b98a6cc_remove_account_type_field_from_account_.py, arbeitszeit_flask/models.py, tests/data_generators.py, tests/flask_integration/database_gateway_impl/test_database_gateway_impl.py, tests/flask_integration/test_account_owner_repository.py, tests/flask_integration/test_company_repository.py, tests/flask_integration/test_member_repository.py, tests/use_cases/repositories.py
This PR removes the redundant field "account_type" from the database. This field used to contain an identifier for the accounts purpose, e.g. "p" for fixed means account or "member" for consumer account. This information is redundant since the purpose of an account can already be determined without that identifier by looking at how the account is linked to a company, member or social accounting.
Plan-ID: 8c5dfb71-affb-4def-b850-aafa86b2c8fd (2x)
=> Remove redundant `account_type` model from database

arbeitszeit/accountant_notifications.py, arbeitszeit/repositories.py, arbeitszeit/use_cases/get_accountant_dashboard.py, arbeitszeit/use_cases/log_in_accountant.py, arbeitszeit/use_cases/register_accountant.py, arbeitszeit/use_cases/send_accountant_registration_token/__init__.py, arbeitszeit_flask/database/repositories.py, tests/flask_integration/test_accountant_repository.py, tests/use_cases/repositories.py
We removed the `has_accountant_with_email` and `get_by_id` methods from AccountantRepository and created a proper AccountantResult interface that offers replacements for the removed methods. Also the `get_all_accountants` method was renamed to `get_accountants` to be more consitent with the naming scheme of the database gateway.
=> Refactor arbeitszeit.repositories.AccountantRepository

docs/development_guide.rst
This change adds a new section to the development guide called "User identification". It provides info basic concepts for user account handling.
=> Add section "User identification" to development guide

arbeitszeit/giro_office.py, arbeitszeit/repositories.py, arbeitszeit/transactions.py, arbeitszeit/use_cases/approve_plan.py, arbeitszeit/use_cases/get_company_summary.py, arbeitszeit/use_cases/pay_means_of_production.py, arbeitszeit/use_cases/send_work_certificates_to_worker.py, arbeitszeit/use_cases/update_plans_and_payout.py, arbeitszeit_flask/database/__init__.py, arbeitszeit_flask/database/repositories.py, arbeitszeit_flask/dependency_injection/__init__.py, tests/data_generators.py, tests/flask_integration/database_gateway_impl/test_database_gateway_impl.py, tests/flask_integration/database_gateway_impl/test_transaction_result.py, tests/use_cases/dependency_injection.py, tests/use_cases/repositories.py, tests/use_cases/test_approve_plan.py, tests/use_cases/test_pay_consumer_product.py, tests/use_cases/test_pay_means_of_production.py, tests/use_cases/test_send_work_certificates_to_worker.py, tests/use_cases/test_update_plans_and_payout.py
This change merges the TransactionRepository interface with the DatabaseGateway interface. This change necessitated also merging the implementations of these interfaces. No functional changes were made. The tests for the sqlalchemy implementation of these interfaces were moved but otherwise left unchanged.
=> Merge TransactionRepository with DatabaseGateway interface

constraints.txt, flake.lock
This change updates the nix flake inputs to the most recent state as of 25th April 2023. The python constraints list `constraints.txt` was update to reflect this change.
=> Update nix flake inputs

tests/use_cases/test_register_company.py
The unit tests for RegisterCompanyUseCase do not depend on repository implementations anymore but instead use the request/response model of different use cases to test for correctness.
=> Tests: Refactor register company tests

arbeitszeit/use_cases/register_member/__init__.py, arbeitszeit_flask/database/repositories.py, arbeitszeit_flask/migrations/versions/fb341bf85b13_move_confirmed_on_from_member_company_.py, arbeitszeit_flask/models.py, arbeitszeit_flask/url_index.py, arbeitszeit_flask/views/signup_member_view.py, arbeitszeit_web/presenters/register_member_presenter.py, arbeitszeit_web/url_index.py, tests/flask_integration/test_url_index.py, tests/presenters/test_register_member_presenter.py, tests/presenters/url_index.py, tests/use_cases/test_register_member.py, type_stubs/flask_login.pyi
The following description is composed from the descriptions of the individual commits of this change set. There is still a lot of work to do with respect to account management and email confirmation. If this PR gets merged I will try to make further changes going in the same direction as the changes presented here.
```
Before this change it was possible to override an existing companies
password by registering a member with the same email address. This
change does not allow this behavior anymore. Instead the registering
member is required to enter the same password as the company already
has set up.
```
```
This change moves the `confirmed_on` fields from the member and
company tables to the user table. A result of this is that companies
and member with the same email address don't need …
```
=> Member password override protection

arbeitszeit/use_cases/register_company/__init__.py, arbeitszeit_web/presenters/register_company_presenter.py, tests/presenters/test_register_company_presenter.py, tests/use_cases/test_register_company.py
Before this change it was possible to change a companies password by registering a member account with the same email address. This possible attack vector is eliminated with this change. The use will see a minimal error message if they try to register a company with the email address of a preexisting member account and the provided password does not match the members password.
=> Implement override protection for company passwords

arbeitszeit_flask/auth/routes.py, arbeitszeit_flask/company/blueprint.py, arbeitszeit_flask/flask_request.py, arbeitszeit_flask/member/blueprint.py, arbeitszeit_flask/url_index.py, arbeitszeit_web/authentication.py, arbeitszeit_web/request.py, arbeitszeit_web/session.py, arbeitszeit_web/url_index.py, tests/flask_integration/test_company_dashboard_view.py, tests/flask_integration/test_company_purchases_view.py, tests/flask_integration/test_login_company_view.py, tests/flask_integration/test_login_member_view.py, tests/flask_integration/test_member_dashboard_view.py, tests/flask_integration/test_member_purchases_view.py, tests/request.py
When accessing a page that requires authentication we redirect users back to the start page and notify them that they need to log in. Previously we would encode the original target url in a url query. With this change we encode the original target location in the session cookie instead.
Also the code for authenticating client requests was moved from the flask specific folder `arbeitszeit_flask` to the folder for framework agnostic web code `arbeitszeit_web`. This allows us to test the redirection logic more easily in later changes to our code.
Plan-ID: 8c5dfb71-affb-4def-b850-aafa86b2c8fd (2x)
=> Encode redirection url after login in cookie instead of url query

arbeitszeit/repositories.py, arbeitszeit/transactions.py, arbeitszeit_flask/database/repositories.py, tests/flask_integration/database_gateway_impl/test_transaction_result.py, tests/use_cases/repositories.py
This changeset introduces a new method on the TransactionResult interface: joined_with_sender_and_receiver.  This method was introduced to optimize the GetCompanyTransactions use case.  Before this change there were two separate DB query for each transaction made from or to a company.  With the new method there is only one single DB query made for all the transactions from/to a company combined. This speeds up the execution time for the use case by orders of magnitude.
Plan-ID: 8c5dfb71-affb-4def-b850-aafa86b2c8fd (3x)
=> Database: Implement method to join Transactions with their sender and receiver

arbeitszeit/repositories.py, arbeitszeit/use_cases/confirm_company.py, arbeitszeit_flask/auth/routes.py, arbeitszeit_flask/database/repositories.py, arbeitszeit_web/authentication.py, tests/data_generators.py, tests/flask_integration/test_company_repository.py, tests/use_cases/repositories.py
This change reworks the CompanyRepository interface. Before this change the CompanyRepository interface provided the `confirm_company` and `is_company_confirmed` methods. The `confirm_company` method was moved to the newly created `CompanyUpdate` interface. The `is_company_confirmed` method was replaced by the
`CompanyResult.that_are_confirmed` method. The implementations were adjusted respectivly.
=> Database: Reorganize CompanyRepository interface

.autoformattingrc, README.rst, arbeitszeit_benchmark/__main__.py, arbeitszeit_benchmark/get_company_transactions.py, arbeitszeit_benchmark/runner.py, pyproject.toml
With this changeset we start providing a basic framework to measure the runtime characteristics of our code. Those benchmarks can be found under `/arbeitszeit_benchmark` and contain one example for now.
I was motivated to do this change because the `arbeitszeitapp` is significantly slowing down when viewing the transaction overview for companies. Here is an excerpt from the profiling output:
Before making any changes to the code I wanted to measure the current performance and compare it to the performance after the changes. The code that resulted from that is provided with this change. I hope that this will be useful in the future when people are optimizing the code for performance.
Here is sample output from the benchmarking app:
```
$ python …
```
=> Implement rudimentary benchmark framework

arbeitszeit/entities.py, arbeitszeit/transactions.py, arbeitszeit/use_cases/show_prd_account_details.py, arbeitszeit_benchmark/__main__.py, arbeitszeit_benchmark/show_prd_account_details_benchmark.py
This change optimizes the ShowPRDAccountDetails use case with regards to DB access.
First I implemented a basic benchmark for the use case and recorded the average time to execute the benchmark:
```json
{
[...],
"show_prd_account_details": {
"name": "show_prd_account_details",
"average_execution_time_in_secs": 6.97218787400052
}
}
```
Afterwards I implemented the fix and recorded the following timing:
```json
{
[...],
"show_prd_account_details": {
"name": "show_prd_account_details",
"average_execution_time_in_secs": 1.416829142998904
}
}
```
This is a speed increase by 500%. I think that this use case could be optimized more since 1.4 seconds sounds like a lot for handling a couple of 100 transactions.
=> Optimize ShowPRDAccountDetails use case

arbeitszeit/entities.py, arbeitszeit/repositories.py, arbeitszeit/use_cases/confirm_company.py, arbeitszeit/use_cases/resend_confirmation_mail.py, arbeitszeit_flask/database/repositories.py, tests/flask_integration/database_gateway_impl/test_company_result.py, tests/flask_integration/database_gateway_impl/test_member_result.py, tests/flask_integration/test_resend_confirmation_view.py, tests/use_cases/repositories.py
This change makes the separation of email info and member/company accounts explicit in the business logic.
Plan-ID: 8c5dfb71-affb-4def-b850-aafa86b2c8fd (2x)
=> Seperate email confirmation info into EmailAddress entity

.github/workflows/python-app.yml, constraints.txt, flake.lock, flake.nix
This change adds support for the nixpkgs branch `nixos-23.05`, which is the current stable version of NixOS as of this commit.
The nix flake inputs where updated.
=> Add CI check for nixos-23.05 package set

arbeitszeit/repositories.py, arbeitszeit/use_cases/delete_draft.py, arbeitszeit/use_cases/edit_draft.py, arbeitszeit/use_cases/file_plan_with_accounting.py, arbeitszeit/use_cases/get_draft_summary.py, arbeitszeit/use_cases/show_my_plans.py, arbeitszeit_flask/database/repositories.py, tests/data_generators.py, tests/flask_integration/test_create_draft_view.py, tests/flask_integration/test_plan_draft_repository.py, tests/use_cases/repositories.py, tests/use_cases/test_create_plan_draft.py
This change brings the PlanDraftRepository more in line with the rest of the repositories.  There is now a `get_plan_drafts` method that returns a "proper" `PlanDraftResult`. These `PlanDraftResult` objects can be filtered by id and planner.
=> Refactor PlanDraftRepository

arbeitszeit_flask/migrations/versions/ed5e327140bf_create_user_model.py
There was a bug in migration ed5e327140bf, this PR fixed it. I ran into this bug after upgrading to NixOS 23.05 in https://github.com/arbeitszeit/arbeitszeitapp-deployment
My guess is that this bug suddenly showed up since NixOS 23.05 ships a newer version of sqlalchemy. I tested this change with the integration tests from https://github.com/arbeitszeit/arbeitszeitapp-deployment and it fixed the migration errors.
=> Fix bug in migration ed5e327140bf

arbeitszeit_flask/auth/routes.py, arbeitszeit_flask/database/repositories.py, arbeitszeit_flask/migrations/versions/7a550048df32_create_email_table.py, arbeitszeit_flask/models.py, type_stubs/flask_login.pyi
This change creates a new database table "email". The purpose of this table is to store information associated with email addresses. This was done in preparation to implement a "change email address" feature for users.
This table will allow us to separate the steps of confirming an email address and changing a users email address.
Plan-ID: 8c5dfb71-affb-4def-b850-aafa86b2c8fd (2x)
=> database: Move email address specific info into new email table

nix/pythonPackages/flask-restx.nix
We used to have the package name and the version of `flask-restx` hardcoded in our nix package directives. With this change the correct metadata is read from the json file `flask-restx.json` that also serves as the source definition for fetchPypi.
Thank @Amittai-Aviram for catching a similar bug with `is_safe_url`. Your discovery gave me the idea to check `flask-restx` as well.
=> fix bug in flask-restx nix packaging directive

tests/datetime_service.py, tests/use_cases/base_test_case.py, tests/use_cases/test_pay_consumer_product.py, tests/use_cases/test_query_member_purchases.py, tests/use_cases/test_show_prd_account_details.py
This change reworks the tests for the
ShowPRDAccountDetailsUseCase. The basic idea of this change was to remove all explicit references to the transaction generator and the transaction repository. Instead the creation of the test fixtures is done by invoking the proper use cases for for "buying" products from a company. This should make the tests more robust in the face of changes to the DB structure.
=> tests: Rework tests for ShowPRDAccountDetailsUseCase

arbeitszeit/repositories.py, arbeitszeit/use_cases/confirm_company.py, arbeitszeit/use_cases/confirm_member.py, arbeitszeit/use_cases/register_accountant.py, arbeitszeit/use_cases/register_company.py, arbeitszeit/use_cases/register_member.py, arbeitszeit_flask/database/repositories.py, tests/data_generators.py, tests/flask_integration/database_gateway_impl/test_company_result.py, tests/flask_integration/database_gateway_impl/test_email_result.py, tests/flask_integration/database_gateway_impl/test_member_result.py, tests/flask_integration/flask.py, tests/use_cases/repositories.py, tests/use_cases/test_list_workers.py, tests/use_cases/test_register_accountant.py, tests/use_cases/test_register_company.py, tests/use_cases/test_register_member.py, tests/use_cases/test_show_a_account_details.py
This change moves the update logic for email addresses in the DB to the newly created EmailAddressUpdate interface. All use cases were updated accordingly.
Plan-ID: a6a663c1-c041-4085-a627-c4f3395928bf (3x)
=> DatabaseGateway: Refactor update logic for email addresses

tests/use_cases/test_get_company_transactions.py
The use case tests for GetCompanyTransactions were not conforming to our standard test suite layout. Current development standards require tests to be based on the pythons unittest.TestCase class. The tests in tests/use_cases/test_get_company_transactions.py were instead based on pytests function based approach. Now they are class based.
Plan-ID: a6a663c1-c041-4085-a627-c4f3395928bf
=> tests: Refactor test_get_company_transactions.py

arbeitszeit/repositories.py, arbeitszeit/use_cases/create_plan_draft.py, arbeitszeit/use_cases/delete_draft.py, arbeitszeit/use_cases/edit_draft.py, arbeitszeit/use_cases/file_plan_with_accounting.py, arbeitszeit/use_cases/get_draft_summary.py, arbeitszeit/use_cases/show_my_plans.py, arbeitszeit_flask/database/repositories.py, arbeitszeit_flask/dependency_injection/__init__.py, tests/data_generators.py, tests/flask_integration/database_gateway_impl/test_plan_draft_result.py, tests/flask_integration/test_create_draft_view.py, tests/flask_integration/test_delete_draft_view.py, tests/flask_integration/test_get_draft_summary_view.py, tests/flask_integration/test_url_index.py, tests/presenters/test_show_my_plans_presenter.py, tests/use_cases/dependency_injection.py, tests/use_cases/repositories.py, tests/use_cases/test_approve_plan.py, tests/use_cases/test_create_plan_draft.py, tests/use_cases/test_delete_draft.py, tests/use_cases/test_edit_draft.py, tests/use_cases/test_file_plan_with_accounting.py, tests/use_cases/test_get_draft_summary.py, tests/use_cases/test_list_plans_with_pending_review.py, tests/use_cases/test_show_my_plans.py
This change removes the PlanDraftRepository interface and its implementations in favor of moving all the associated functionality to DatabaseGateway and its implementations.
Futher the PlanGenerator was changed slightly such that draft_plan no longer returns a Plan entity object but a UUID instead.
Plan-ID: a6a663c1-c041-4085-a627-c4f3395928bf
=> Remove PlanDraftRespository

arbeitszeit/entities.py, arbeitszeit/use_cases/get_user_account_details.py, arbeitszeit_flask/member/routes.py, arbeitszeit_flask/templates/base_member.html, arbeitszeit_flask/templates/member/get_member_account_details.html, arbeitszeit_web/controllers/get_member_account_details_controller.py, arbeitszeit_web/presenters/get_member_account_details_presenter.py, tests/controllers/test_get_member_account_details_controller.py, tests/flask_integration/test_get_member_account_details_view.py, tests/presenters/test_get_member_account_details_presenter.py, tests/use_cases/test_get_user_account_details.py
The goal of this PR is to create the conditions for implementing functionality that lets the user change their email address and password. To this end I implemented a basic minimal "account settings" view. The layout of this view is super minimal and should be polished in future changes.
Here is a preview of this new view:
It can be accessed by clicking on the user name that is displayed in the top left corner at all times.
Here are the commit messages of the 2 commits included in this PR:
The implemented use case class is supposed to show basic account
information to the user. In this first iteration the information
returned is limited to the users ID and email address.
With this change a new view is introduced. This view allows users
logged in as a member to check their basic account …
=> Implement member account details view

arbeitszeit_flask/company/routes.py, arbeitszeit_flask/templates/base_company.html, arbeitszeit_flask/templates/base_member.html, arbeitszeit_flask/templates/company/get_company_account_details.html, arbeitszeit_web/www/controllers/get_company_account_details_controller.py, arbeitszeit_web/www/presenters/get_company_account_details_presenter.py, tests/controllers/test_get_company_account_details_controller.py, tests/flask_integration/test_get_company_account_details_view.py, tests/presenters/test_get_company_account_details_presenter.py
This change implements a web view where companies can see their user id and email address. The added code implements the adapter logic for the get_user_account_details use case.
Plan-ID: a6a663c1-c041-4085-a627-c4f3395928bf (2x)
=> Implement account details view for companies

arbeitszeit_flask/accountant/routes.py, arbeitszeit_flask/templates/accountant/get_accountant_account_details.html, arbeitszeit_flask/templates/base_accountant.html, arbeitszeit_web/www/controllers/get_accountant_account_details_controller.py, arbeitszeit_web/www/presenters/get_accountant_account_details_presenter.py, tests/controllers/test_get_accountant_account_details_controller.py, tests/flask_integration/test_get_accountant_account_details_view.py, tests/presenters/test_get_accountant_account_details_presenter.py
The implemented controller, presenter and flask route allow accountants to review their on account info, which is at the moment only their own email address and their user id.
Plan-ID: a6a663c1-c041-4085-a627-c4f3395928bf
=> Implement GetAccountantAccountDetails view

arbeitszeit/entities.py, arbeitszeit/payout_factor.py, arbeitszeit/repositories.py, arbeitszeit/use_cases/get_statistics.py, arbeitszeit_benchmark/__main__.py, arbeitszeit_benchmark/get_statistics.py, arbeitszeit_benchmark/runner.py, arbeitszeit_flask/database/repositories.py, tests/flask_integration/test_account_repository.py, tests/use_cases/repositories.py
This change optimizes the runtime characteristics of the `GetStatistics` use case. The first commit implements a benchmark test to measure eventual performance changes. The second commit introduces a whole bunch of optimizations. The single optimization that gave the most performance gain was the change towards retrieving multiple account balances from the database all in one sql query instead of querying the accounts of companies and members individually.
Plan-ID: a6a663c1-c041-4085-a627-c4f3395928bf (3x)
=> Optimize GetStatistics

build_support/translations.py
This is a small change to resolve issue 850, in which the problem was that the routines to initialize and update translations were using absolute paths, and therefore writing configuration files that contained information specific to a single developer's machine.  This PR does not include any changes to tests, because the one test we have (in tests/translator.py) tests translator functionality rather than infrastructure.
=> Use Relative Paths for Translation Routines

arbeitszeit_flask/database/repositories.py, tests/flask_integration/database_gateway_impl/test_private_consumption_result.py, tests/flask_integration/database_gateway_impl/test_productive_consumption_result.py
Four methods of the `ProductiveConsumptionResult` and `PrivateConsumptionResult` classes have been implemented in our flask database layer.  Corresponding tests have been added. The existing database tests of both "Result" classes have been moved into separate modules.
Plan: fd00d0bb-0ea3-4338-b097-dfa605278f1c (3x)
=> Implement db methods for private and productive consumption

arbeitszeit/use_cases/review_registered_consumptions.py, arbeitszeit_flask/company/routes.py, arbeitszeit_flask/templates/company/review_registered_consumptions.html, arbeitszeit_flask/views/review_registered_consumptions_view.py, arbeitszeit_web/www/controllers/review_registered_consumptions_controller.py, arbeitszeit_web/www/presenters/review_registered_consumptions_presenter.py, tests/flask_integration/test_review_registered_consumptions_view.py, tests/use_cases/test_review_registered_consumptions.py, tests/www/controllers/test_review_registered_consumptions_controller.py, tests/www/presenters/test_review_registered_consumptions_presenter.py
**Fix typo in class definition: Rewiew -> Review**
**Implement ReviewRegisteredConsumptionsView** 
This commit adds a company route ("/company/review_registered_consumptions") which leads to the `ReviewRegisteredConsumptionsView`. The corresponding controller has been refactored in order to return the correct status codes (401, 403).
There is still no content in the html file and there is no place in the app that links to the new route. This will be implemented in one of the upcoming PRs. 
Plan: fd00d0bb-0ea3-4338-b097-dfa605278f1c
=> Implement new route ("Review registered consumption") and fix typo

arbeitszeit_flask/__init__.py, arbeitszeit_flask/configuration_base.py, arbeitszeit_flask/templates/base.html, arbeitszeit_flask/templates/user/request_email_address_change.html, tests/flask_integration/flask.py, tests/flask_integration/test_private_consumptions_view.py
In the past our app did crash or behave unexpectedly because of errors in our jinja templates. For example when we would loop over undefined variables or used a mistyped variable in a template.  A current example is described in issue #921.
In order to be able to catch these errors in our tests we set the `undefined` paramter of the jinja environment of this app to `StrictUndefined` https://jinja.palletsprojects.com/en/3.0.x/api/#undefined-types
We also fix the places where the new configuration raises errors. In the `configuration_base.py` we have to insert four dummy config entries until a bug in flask-restx is fixed.
Plan: fd00d0bb-0ea3-4338-b097-dfa605278f1c (4x)
=> Add strict undefined behavior for Jinja2 environment

.github/workflows/python-app.yml
This change should fix the problem that our CI pipeline wouldn't run on pull requests from forks.
Details: https://docs.github.com/de/actions/using-workflows/events-that-trigger-workflows#pull_request
=> Run github CI workflow on pull requests

arbeitszeit/use_cases/register_productive_consumption.py, arbeitszeit_flask/api/__init__.py, arbeitszeit_flask/api/companies.py, arbeitszeit_flask/api/consumptions.py, arbeitszeit_flask/api/input_documentation.py, arbeitszeit_web/api/controllers/liquid_means_consumption_controller.py, arbeitszeit_web/api/controllers/query_companies_api_controller.py, arbeitszeit_web/api/controllers/query_plans_api_controller.py, arbeitszeit_web/api/presenters/liquid_means_consumption_presenter.py, arbeitszeit_web/api/response_errors.py, tests/api/controllers/test_liquid_means_consumption_controller.py, tests/api/controllers/test_query_companies_api_controller.py, tests/api/controllers/test_query_plans_api_controller.py, tests/api/integration/base_test_case.py, tests/api/integration/test_liquid_means_consumption.py, tests/api/integration/test_list_active_plans_api.py, tests/api/integration/test_query_companies_api.py, tests/api/presenters/test_liquid_means_consumption_presenter.py
**API: Add missing documentation and some tests** 
The get route for companies was missing the documentation of the 401 error. Also tests for offset and limit parameters were added. The automatically generated OpenAPI documentation for the input parameters "offset" and "limit"
was changed in order to show that we expect integers.
**New API endpoint consumptions** 
This commit creates a new endpoint for our RestAPI, `/consumptions`, and implements also a route for this endpoint, `/consumptions/liquid_means_of_production`. This route accepts only POST requests and can be used by authenticated companies to register consumption of liquid means of production ("raw materials").
For this POST method we are using the existing `RegisterProductiveConsumption` use case from the business logic layer …
=> New API endpoint `consumptions`

arbeitszeit_flask/forms.py, arbeitszeit_flask/templates/macros/draft_form.html, arbeitszeit_flask/views/create_draft_view.py
This commit adds placeholders to the `CreateDraftForm`. The text "Days" appear in the field "planning timeframe" and the text "Hours" appear in fields "cost_p", "cost_r" and "cost_a".
No registration needed.
=> Add placeholders in plan draft creation forms

arbeitszeit_flask/templates/user/company_account_a.html, arbeitszeit_flask/templates/user/company_account_p.html, arbeitszeit_flask/templates/user/company_account_prd.html, arbeitszeit_flask/templates/user/company_account_r.html, arbeitszeit_flask/templates/user/company_accounts.html
Before this commit balances of company accounts p, r, a and prd were shown green when value was >= 0 and red when <0. This was misleading, because it potentially shows a "green light" for misplanning (less consumption of means of production, less worked hours, more product delivered than originally planned, etc.). The real goal of planning is to be near zero. 
The company balances are now always non-colored. Green and red coloring has been maintained for transactions (it's easier in order to distinguish between positive and negative numbers) and for the member account (here it is more probable that it is problematic if a worker consumes more than the amount of available work certificates).
Plan: b05bef9c-4dbf-4cd1-9e99-59219dfa9c4b
=> Non-colored balances of company accounts

arbeitszeit_flask/views/query_plans.py, tests/flask_integration/test_query_companies_view.py, tests/flask_integration/test_query_plans_view.py
In the QueryPlansView we were passing `request.form` instead of `request.args` to the PlanSearchForm. This was incorrect because we are dealing with a GET request and key word arguments.
The bug has been fixed and integration tests have been added.
Plan: b05bef9c-4dbf-4cd1-9e99-59219dfa9c4b (2x)
=> Fix bug in QueryPlansView

arbeitszeit_web/www/presenters/request_email_address_change_presenter.py, tests/www/presenters/test_request_email_address_change_presenter.py
Before this change it was not clear for users that their request for an email address change has been accepted and that a confirmation mail has been sent out.
=> Add info message for successful email address change request

README.rst, arbeitszeit_flask/configuration_base.py, arbeitszeit_flask/translations/de/LC_MESSAGES/messages.po, arbeitszeit_flask/translations/en/LC_MESSAGES/messages.po, arbeitszeit_flask/translations/es/LC_MESSAGES/messages.po, arbeitszeit_flask/translations/messages.pot, tests/flask_integration/dependency_injection.py, tests/flask_integration/test_language_repository.py
This PR updates German translations, adds support for Spanish and translates all strings to Spanish. As documented in the README, I found a gettext extension for VS Code that was very helpful in combination with a LLM. While a Spanish native speaker might find some smaller issues in the translations, it should be good enough for now.  
Commits:
- Update pot and po files
- Update translations for German language
- Add Spanish language support
- Translate app to Spanish
Plan: b05bef9c-4dbf-4cd1-9e99-59219dfa9c4b (4x)
=> Translate app to Spanish

arbeitszeit/use_cases/show_p_account_details.py, arbeitszeit_flask/templates/user/company_account_p.html, arbeitszeit_web/www/presenters/show_p_account_details_presenter.py, tests/use_cases/test_show_p_account_details.py, tests/www/presenters/test_show_p_account_details.py
In commit efae6e4 we added some additional info to the company p accounts (sum of planned and consumed p). These additions get reverted in the current commit.
=> Undo adding info on p account

arbeitszeit_web/www/controllers/list_registered_hours_worked_controller.py, arbeitszeit_web/www/presenters/list_registered_hours_worked_presenter.py, tests/www/controllers/test_list_registered_hours_worked_controller.py, tests/www/presenters/test_list_registered_hours_worked_presenter.py
**Add ListRegisteredHoursWorkedController** 
This commit adds the `ListRegisteredHoursWorkedController` class, which is responsible for creating a request object for the `list_registered_hours_worked` use case. The controller retrieves the current user role and company from the session and asserts that the current user role is `company`. The company ID is then passed as a parameter to the request object.
See issue #1029 for context.
**Add ListRegisteredHoursWorkedPresenter** 
This commit adds the `ListRegisteredHoursWorkedPresenter` class, which is responsible for presenting the response of the `list_registered_hours_worked` use case. The presenter formats the registered hours worked data, including rounding decimal hours to two decimals and converting worker IDs to strings. This …
=> List registered hours worked (www layer)

arbeitszeit_flask/database/repositories.py
When running our unittests, SQLAlchemy would raise a warning ("SAWarning: SELECT statement has a cartesian product ..."). This gets fixed in this commit.
```
tests/flask_integration/database_gateway_impl/test_registered_hours_worked_result.py::RegisteredHoursWorkedResultTests::test_that_result_joined_with_worker_has_correct_worker_id
tests/flask_integration/database_gateway_impl/test_registered_hours_worked_result.py::RegisteredHoursWorkedResultTests::test_that_result_joined_with_worker_has_correct_worker_name_0_name1
tests/flask_integration/database_gateway_impl/test_registered_hours_worked_result.py::RegisteredHoursWorkedResultTests::test_that_result_joined_with_worker_has_correct_worker_name_1_other_name
arbeitszeit_flask/database/repositories.py:53: SAWarning: SELECT statement has a …
```
=> Fix test run warning (sqlalchemy)

arbeitszeit_flask/auth/routes.py, tests/flask_integration/test_login_accountant_view.py, tests/flask_integration/test_login_company_view.py, tests/flask_integration/test_login_member_view.py
Before this change we would return 200 when a user (member, company or accountent) provided a wrong password and/or email address on login. Now we return status code 401.
Plan: 371825c0-3112-47cd-9cb0-fea799fad3ee
=> Return status code 401 on failed login

arbeitszeit_flask/templates/company/my_cooperations.html
A picture says more than a thousand words ;)
**Before this fix:**
**After this fix:**
I don't now if the margin of the icon, concerning the button size was before #1039 like this. Looks in my opinion a little weird, because the buttons look kind of big. But this type of question is something I would touch in #1035 and transform into something else that looks different from todays status quo anyways. Therefore I would suggest to postpone such styling questions for now.
=> Fix incorrect merge conflict resolution that rendered the icon useless

arbeitszeit_flask/filters.py
This pull request refactors the `icon_filter` function and associated file reader to use `importlib.resources`, to ensure consistent handling of resource files within the app (Flask framework layer). This change addresses the issue of incorrect file paths, especially in production setups where package installation paths can vary.
- **Previous Implementation:**
- The `icon_filter` function relied on a hardcoded relative path to locate SVG files. This approach assumed a specific directory structure, which led to an issue in deployment #1056.
The conclusion in the above-mentioned issue was that the code attempted to read files via a naive path string, which is not sufficient for use across different environments, causing a `FileNotFoundError` in our production environment.
- **New …
=> Fix icon path resolution

arbeitszeit_flask/views/register_productive_consumption.py, tests/flask_integration/test_register_productive_consumption_view.py
This commit enhances the GET method of `RegisterProductiveConsumptionView` to accept a query parameter "plan_id" and pre-fill the plan_id field of the web form.
#1053
=> Query param "plan_id" for productive consumption

arbeitszeit_flask/filters.py, tests/flask_integration/test_filters.py
As decided at our in-person RIDAA meeting today, I changed the icon filter code in a way that it is also raising exceptions in production. This way, problems will already show in the CI/CD process.
=> Let icon filter also raise exceptions in production

arbeitszeit_flask/views/register_productive_consumption.py, tests/flask_integration/test_register_productive_consumption_view.py
Before this change we would return code 200 when productive consumptions got rejected due to any of the rejection reasons listed in `RegisterProductiveConsumptionResponse.RejectionReason`.
This has been changed to return 400 instead.
#1053
Plan: 371825c0-3112-47cd-9cb0-fea799fad3ee
=> Return 400 on rejected productive consumption

arbeitszeit_flask/views/register_hours_worked_view.py, arbeitszeit_web/www/presenters/register_hours_worked_presenter.py, tests/flask_integration/test_register_hours_worked_view.py, tests/www/presenters/test_register_hours_worked_presenter.py
This commit prevents re-submitting the post form in `/company/register_hours_worked` when using back-button in browser.
Fixes #1054
=> Prevent re-submitting form

arbeitszeit/use_cases/get_member_dashboard.py, arbeitszeit_flask/templates/member/dashboard.html, arbeitszeit_web/www/presenters/get_member_dashboard_presenter.py, tests/use_cases/test_get_member_dashboard.py, tests/www/presenters/test_get_member_dashboard_presenter.py
_To be reviewed after merge of https://github.com/ida-arbeitszeit/arbeitszeitapp/pull/1079_
**Replace workplace email with url** 
Members have on their dashboard a list of their workplaces. Before this commit, the email address of these workplaces were shown. Now, a link to the company summary page of their workplace is shown instead (where the email address can be seen).
Plan: 8ec03a5b-3dbe-465d-a533-4b3bfe16121b (1x)
=> Replace workplace email with url

arbeitszeit/use_cases/select_productive_consumption.py, arbeitszeit_flask/templates/company/register_productive_consumption.html, arbeitszeit_flask/views/register_productive_consumption.py, arbeitszeit_web/www/controllers/select_productive_consumption_controller.py, arbeitszeit_web/www/presenters/select_productive_consumption_presenter.py, tests/flask_integration/test_register_productive_consumption_view.py, tests/flask_integration/test_url_index.py, tests/use_cases/test_select_productive_consumption.py, tests/www/controllers/test_select_productive_consumption_controller.py, tests/www/presenters/test_select_productive_consumption_presenter.py
This commit creates SelectProductiveConsumptionUseCase, -Presenter and -Controller and uses these in the RegisterProductiveConsumptionView. They are intended to handle the GET part of this view, leaving POST mostly untouched.
It implements a user flow described in issue #1053. New features:
* The user sees some plan info before they have the chance to register consumption.
* The provided plan ID appears as a read-only form field if it is valid.
* There are two new buttons ("Select" and "Cancel").
That is IMO quite a lot of (quite complex) code for a not-so-huge change. Until now it took me around 25 hours (including failed attempts) and I'm still not really happy with the outcome. Perhaps we can discuss in one of our next meetings if this is a necessary consequence of clean architecture …
=> Implement selection of productive consumption

arbeitszeit/use_cases/invite_worker_to_company.py, arbeitszeit_flask/forms.py, arbeitszeit_flask/templates/company/invite_worker_to_company.html, arbeitszeit_flask/views/invite_worker_to_company.py, arbeitszeit_web/forms.py, arbeitszeit_web/www/controllers/invite_worker_to_company_controller.py, arbeitszeit_web/www/presenters/invite_worker_to_company_presenter.py, tests/flask_integration/test_company_work_invite_view.py, tests/flask_integration/test_invite_worker_to_company_view.py, tests/flask_integration/test_url_index.py, tests/use_cases/test_answer_company_work_invite.py, tests/use_cases/test_get_member_dashboard.py, tests/use_cases/test_invite_worker_to_company.py, tests/use_cases/test_show_company_work_invite.py, tests/use_cases/test_show_work_invites.py, tests/www/controllers/test_invite_worker_to_company_controller.py, tests/www/presenters/test_invite_worker_to_company.py
After this change the `InviteWorkerToCompanyUseCase` returns explicit rejection reasons to improve the error handling in the presenter.
The flask-layer view  `InviteWorkerToCompanyView` has been changed to redirect on successful POST request instead of returning 200.
Should fix all problems described in #1081.
Plan: 8ec03a5b-3dbe-465d-a533-4b3bfe16121b (6x)
=> Improve worker invitation

arbeitszeit_flask/database/repositories.py, tests/flask_integration/database_gateway_impl/test_plan_results.py, tests/flask_integration/test_query_plans_view.py
Before this change it was not possible to order a plan result by planner name AND join it with planner, cooperation and cooperating plans because a  `psycopg2.errors.GroupingError` would be raised.  Grouping has been added in the `ordered_by_planner_name` method to prevent this.
fixes #1093
Plan: 8ec03a5b-3dbe-465d-a533-4b3bfe16121b (3x)
=> Fix bug in PlanQueryResult

arbeitszeit/use_cases/query_plans.py, arbeitszeit_benchmark/query_plans_sorted_by_activation_date_benchmark.py, arbeitszeit_flask/forms.py, arbeitszeit_flask/templates/user/query_plans.html, arbeitszeit_web/api/controllers/query_plans_api_controller.py, arbeitszeit_web/query_plans.py, tests/use_cases/test_approve_plan.py, tests/use_cases/test_query_plans.py, tests/www/controllers/test_query_plans_controller.py, tests/www/presenters/data_generators.py, tests/www/presenters/test_query_plans_presenter.py
This commit changes the `QueryPlans` Use Case to search also for expired plans, if specified in the request.
The use case test has been refactored for easier testing of different search strategies.
Html, controller and presenter have been adapted as well.
Fixes #1096
Plan: 8ec03a5b-3dbe-465d-a533-4b3bfe16121b (8x)
=> Allow to search for expired plans

arbeitszeit/use_cases/query_plans.py, tests/use_cases/test_query_plans.py
Calculation of total number of queried plans (`total_results`) has to be calculated AFTER the filtering took place.
See also this comment: https://github.com/ida-arbeitszeit/arbeitszeitapp/pull/1101#discussion_r1826591814
Plan: 8ec03a5b-3dbe-465d-a533-4b3bfe16121b
=> Fix bug of incorrect `total_results` of queried plans

tests/use_cases/test_query_plans.py
Testcase  `test_zero_total_results_when_single_plan_filtered_by_id` failed when the randomly generated plan uuid contained "123". Now we query a unique string.
=> Fix flaky use case test in `test_query_plans.py`

nix/devShell.nix
I am adding this since for some reason, after latest dependencies update, my setup with hub installed via homebrew and direnv does not work anymore. Executing 'git status' returned error: tool 'git' not found.
=> add git to dev shell environment

arbeitszeit_flask/api/input_documentation.py, arbeitszeit_web/api/controllers/liquid_means_consumption_controller.py, arbeitszeit_web/api/controllers/login_company_api_controller.py, arbeitszeit_web/api/controllers/login_member_api_controller.py, arbeitszeit_web/api/controllers/parameters.py, tests/api/controllers/test_liquid_means_consumption_controller.py, tests/api/controllers/test_login_company_api_controller.py, tests/api/controllers/test_login_member_api_controller.py
**Rename Api FormParameter to BodyParameter** 
This is a better name for the parameter in question. Its location is the body of a request and is to be distinguished from a Form parameter. See swagger v2 specs.
**Refactor Api docu decorator** 
This commit refactors the decorator `with_input_documentation`, which is responsible for generating the API documentation of the expected parameters. Now the decorator does not rely on the deprecated flask restx `RequestParser` anymore.
fixes #1111 
_FYI, a good tool to check the generated swagger.json document (http://127.0.0.1:5000/api/v1/swagger.json) for errors is https://editor.swagger.io/_
=> Remove usage of flask restx `RequestParser`

arbeitszeit/plan_details.py, arbeitszeit/price_calculator.py, arbeitszeit/records.py, arbeitszeit/repositories.py, arbeitszeit/use_cases/get_coop_summary.py, arbeitszeit/use_cases/query_plans.py, arbeitszeit/use_cases/register_private_consumption.py, arbeitszeit/use_cases/register_productive_consumption.py, arbeitszeit_flask/database/repositories.py, docs/development_guide.rst, tests/flask_integration/database_gateway_impl/test_plan_results.py, tests/services/test_price_calculator.py, tests/use_cases/repositories.py, tests/use_cases/test_get_plan_details.py
**Rework cooperative price calculation** 
Before this commit, the cooperative price calculation was dependent on the plan durations. Specifically, plan costs were inversely weighted by plan duration, meaning that shorter plans had a greater impact on the coop price than longer running plans. The reasoning behind this was that shorter plans would be renewed more often and contribute more labor time to the cooperation's product.
This commit proposes to reject this original reasoning. We think it made to many unnecessary assumptions on the plans in a cooperation. Instead, we argue that the cooperative price should simply reflect the relation between costs (in labor time) and amount of produced units in a cooperation at a specific point in time. A section explaining the current calculation …
=> Rework cooperative price calculation

arbeitszeit/use_cases/edit_draft.py, arbeitszeit/use_cases/get_draft_details.py, arbeitszeit_flask/templates/company/draft_details.html, arbeitszeit_flask/views/draft_details_view.py, arbeitszeit_web/www/presenters/edit_draft_presenter.py, arbeitszeit_web/www/presenters/get_draft_details_presenter.py, tests/use_cases/test_edit_draft.py, tests/www/presenters/test_edit_draft_presenter.py, tests/www/presenters/test_get_draft_details_presenter.py
The following two commits are preliminary work for #945:
**Delete unnecessary `save_draft_url` in `draft_details.html`** 
This variable in the html form is a relic from past implementations.
**Improve `EditDraftUseCase` by returning rejection reasons**
=> Small changes to draft details and draft edit

MANIFEST.in
Our deployment tests are currently failing. This PR should fix it. 
Output of `nix flake check` in repository `arbeitszeit-deployment`:
```bash
machine # [   23.183504] uwsgi[975]:   File "/nix/store/3w7gq1xrqymlg9wc2i2ga4f1v0izqdn7-python3-3.11.10-env/lib/python3.11/site-packages/arbeitszeit_flask/wsgi.py", line 3, in <modu>
machine # [   23.188221] uwsgi[975]:     app = create_app()
machine # [   23.189692] uwsgi[975]:           ^^^^^^^^^^^^
machine # [   23.192629] uwsgi[975]:   File "/nix/store/3w7gq1xrqymlg9wc2i2ga4f1v0izqdn7-python3-3.11.10-env/lib/python3.11/site-packages/arbeitszeit_flask/__init__.py", line 80, in >
machine # [   23.197736] uwsgi[975]:     alembic_command.upgrade(alembic_cfg, "head")
machine # [   23.200320] uwsgi[975]:   File …
```
=> Add alembic.ini to MANIFEST.in for inclusion in package distribution

tests/flask_integration/database_gateway_impl/test_email_result.py, tests/flask_integration/database_gateway_impl/test_member_result.py
When running our tests via pytest, three tests in our testsuite show "sqlalchemy.exc.SAWarning"  in the test report. This is because we are trying to create a second email address with the same primary key. This commit filters the warnings.
The filtering happens on testcase level. The alternative, filtering via an entry in the `pyproject.toml` file was rejected as being considered too general.
=> Filter SAWarning in pytest report

pyproject.toml
The library flask-restx is raising a warning, that jsonschema.RefResolver is deprecated. It is shown in our pytest reports. We are filtering this message out, because the maintainers are working on it.
=> Filter deprecation warning

arbeitszeit_flask/database/db.py
Before this commit reconfiguring the Database with a new uri failed silently: While the new uri was saved as a property, the engine did not pick it up. Now it fails explicitly.
=> Raise exception on db reconfiguration

arbeitszeit_flask/__init__.py, arbeitszeit_flask/migrations/auto_migrate.py, arbeitszeit_flask/migrations/env.py, tests/flask_integration/dependency_injection.py, tests/flask_integration/flask.py, tests/flask_integration/test_db_migrations.py
**Add test for startup w/ auto_migrate = True**
**Fix bug in auto migration** 
Before this commit, the AUTO_MIGRATE config option did not work as expected for the test or the production db, because our migration tool alembic would migrate always the dev db. Now the correct db engine is passed to the migration script in `arbeitszeit_flask.migrations.env.py`, to make sure that the correct db is auto migrated.
Moreover, when auto migrating, alembic now "stamps" databases that were not initialized with alembic, to enable the migration on that db.
=> Fix bug in auto migration

docs/concepts.rst, docs/development_guide.rst, docs/index.rst
Create a new section in the developer documentation called "concepts". It is intended to provide developers with info on non-self-evident concepts of the app.
Add basic documentation on the concepts of plans and consumption. The docu on cooperation has been moved into the new section.
fixes #1141
=> Add "concepts" section to dev documentation

arbeitszeit_flask/__init__.py, arbeitszeit_flask/database/db.py, arbeitszeit_flask/migrations/auto_migrate.py, arbeitszeit_flask/migrations/versions/15d33dfe8ec7_.py, arbeitszeit_flask/migrations/versions/3b00c719fe52_remove_obsolete_field_plan_active_days.py, arbeitszeit_flask/migrations/versions/8245d6c57ca5_create_registered_hours_worked_table.py, arbeitszeit_flask/migrations/versions/c917f02f0e95_introduce_coordination_tenure_table.py
**Do not stamp db to "head"** 
Do not stamp databases with alembic version of “head” when auto migrating. This leads to skipping of all missing migrations in the respective database, because Alembic sees the database as already up-to-date and does not upgrade.
Instead only create the alembic version table if it does not exist. This ensures that databases without alembic version table can get migrated as well.
**Refactor database initialization and migration logic** 
Modify database setup to support either auto-migration OR direct table creation, in `create_app` function. Removing the separate init_db function.
Before this refactoring, `nix flake check` would fail in `test_that_app_starts_successfully_with_auto_migrate`, beause alembic tries to create tables when they have already been …
=> Migrations - Do not stamp db

arbeitszeit_flask/templates/macros/tooltips.html
Changed it to type="button" to prevent submitting the form when clicked.
fixes #1185
=> Change info_tooltip button type

arbeitszeit/transfers/transfer_type.py
This class enumerates all possible transfer types. The names of the indiviual types are intended to be as short and comprehensible as possible. E.g., I chose the name `taxes` over more correct, but less  comprehensible alternatives.
The possible transfer types are deducted from the discussion in "RFC - Design of accounts and transactions" #1175
fixes #1198
=> Create TransferType enum

tests/data_generators.py, tests/economic_scenarios.py, tests/services/test_psf_balance_service.py, tests/use_cases/base_test_case.py
**Create new test module economic_scenarios.py** 
Currently we are using for test setup mainly the data generators from `tests.data_generators.py`. We have currently no place where we can define more complex test setups that build on top of these data generators. To this end a new `tests.economic_scenarios.py` module has been created.
For now, it provides one method, `setup_environment_with_fic`, which sets up a testing environment with plans that result in a specific FIC value.
**Add tests for public sector fund** 
This commit adds tests for the public sector fund. They are testing the psf balance using abstract business logic (use cases and services) instead of transactions directly, which is more stable and reliable. This abstract testing approach will be necessary when we model wages …
=> Testing public sector fund

arbeitszeit/use_cases/get_statistics.py, arbeitszeit_benchmark/get_statistics.py, arbeitszeit_flask/templates/user/statistics.html, arbeitszeit_flask/views/get_statistics_view.py, arbeitszeit_web/www/presenters/get_statistics_presenter.py, tests/economic_scenarios.py, tests/use_cases/test_get_statistics.py, tests/www/presenters/test_get_statistics_presenter.py
- Docstrings have been added to the Use Case
- Use Case response variable  `available_product` has been renamed to `available_product_in_productive_sector`
- The Use Case was poorly tested. Tests have been added
- Tests have been refactored so that every metric is tested in its own python class
=> Refactor GetStatisticsUseCase and improve tests

arbeitszeit/records.py, arbeitszeit/repositories.py, arbeitszeit/transfers/transfer_type.py, arbeitszeit/use_cases/register_hours_worked.py, arbeitszeit_flask/database/models.py, arbeitszeit_flask/database/repositories.py, arbeitszeit_flask/migrations/versions/0f1f3b156d62_delete_old_database_types.py, arbeitszeit_flask/migrations/versions/d6f685a49a41_add_column_transfer_type.py, tests/data_generators.py, tests/flask_integration/database_gateway_impl/test_transfer_query_result.py, tests/flask_integration/flask.py, tests/use_cases/repositories.py
- Add "type" field to transfer record 
Transfers of labour time can only be of certain, limited types. It therefore makes sense to add an enum field "type" to the transfer record in order to distinguish between different kind of transfers without the need of elaborated database joins, etc. In the future, with arrival of undo-transfers or other new transfer types, it may be even impossible to distinguish between type of transfers without this new field.
fixes #1219
- Remove old database types 
This commit deletes the unused database types 'accounttypes' and 'useraction' from the db via a migration script.
=> Add transfer type

docs/concepts.rst
The "Plans" section in the dev docs in "concepts.rst" has been expanded and refactored.
=> Change "Plans" section in dev docs

arbeitszeit_flask/__init__.py, arbeitszeit_flask/migrations/auto_migrate.py, tests/flask_integration/dependency_injection.py, tests/flask_integration/flask.py, tests/flask_integration/test_db_migrations.py
This commit adds a new base test class, "DatabaseTestCase", which is intended to be used for database tests that do not need access to the flask app.
Furthermore the commit enhances the test isolation of integration tests by implementing a connection-level transaction in the new base test class, which gets rolled back in the `tearDown` method.
While all changes to the database in the tests are rolled back, the table creation, that happens in the create_app function, does not get rolled back. Keeping the tables between test runs allows for considerable better performance compared to before, where we dropped all tables after each test to achieve test isolation. On the authors machine, the `pytest` command now takes only 1:10 instead of 4:10 minutes.
=> Improve test isolation and performance of db and flask tests

arbeitszeit_benchmark/get_company_summary_benchmark.py, arbeitszeit_benchmark/get_statistics.py, arbeitszeit_benchmark/query_plans_sorted_by_activation_date_benchmark.py, arbeitszeit_benchmark/show_prd_account_details_benchmark.py, arbeitszeit_benchmark/show_r_account_details_benchmark.py
Instead of commiting the generated objects in the benchmark tests to the database with commit(), it is preferable to just use flush().
=> Use session.flush() in benchmarks

docs/concepts.rst
- Standardize format in docs/concepts.rst 
We experienced formatting issues that should be fixed by standardizing the format of concepts.rst. Mainly:
- Do not break long lines
- Use `*` instead of `-` for bullet points
- Improve section on Accounts in dev docs
=> Explain accounts in dev docs

arbeitszeit_flask/__init__.py, arbeitszeit_flask/migrations/auto_migrate.py
This commit ensures that migrations that are running in a production setting and AUTO_MIGRATE set to true, will be committed to the database.
=> Commit migrations when auto-migrating

arbeitszeit_flask/database/models.py, arbeitszeit_flask/migrations/versions/9ab8e18b4d0e_non_nullable_transactions_in_.py
They where mistakenly nullable in the sqlalchemy table definitions. Also a migration has been added to ensure that these columns are non-nullable.
=> Make transactions in db consumption tables non nullable

arbeitszeit/use_cases/show_prd_account_details.py, arbeitszeit_web/www/presenters/show_prd_account_details_presenter.py, tests/use_cases/base_test_case.py, tests/use_cases/test_show_prd_account_details.py, tests/www/presenters/test_show_prd_account_details_presenter.py
**Show compensations in ShowPRDAccountDetailsUseCase** 
In order to be able to test this implementation we must create transfers directly instead of making use of the PrivateConsumption use case, which would be preferable, because compensation transfers are not yet implemented in that use case.
Part of https://github.com/ida-arbeitszeit/arbeitszeitapp/issues/1229
=> Show compensations in ShowPRDAccountDetailsUseCase

tests/data_generators.py, tests/use_cases/test_end_cooperation.py, tests/use_cases/test_list_coordinations_of_company.py
Before this change the test data generator "CooperationGenerator" would rely on database operations to assign plans to a cooperation. Instead, it should rely on the use case path, because it prevents data generator user from unsupported operations like adding public plans to cooperations, adding plans to several cooperations, etc. The Generator has been changed. Moreover, the PlanGenerator has been refactored.
=> Rely on use cases in data generator

README.rst, docs/how_to_contribute.rst, docs/introduction.rst
- Separate top-level README and "Introduction" section in dev docs to clarify their distinct purposes
- Add information about the arbeitszeitapp collective to the Introduction section
- Revise "How to contribute" section: explain the milestones workflow and streamline existing content
=> Update dev documentation

.flaskenv, arbeitszeit_flask/commands.py, docs/development_setup.rst, tests/development_server.py, tests/flask_integration/dev_cli.py, tests/flask_integration/test_data_generation_cli.py
With this commit we enhance the flask dev server by registering a data generation CLI on it. This CLI uses internally the data generators from the `tests` folder, which in turn use the domain logic (use cases), to create records like companies or plans in the development database. By using the domain logic we make sure to only create consistent data.
Run `flask generate --help` for more information.
The data generation CLI code is located entirely in the tests folder and thus cannot get accidentally rolled out and used in the production environment.
=> Provide dev server with data generation CLI

arbeitszeit_flask/templates/user/company_accounts.html
Before this commit, icons in the company accounts view had unnecessary svg attributes that would render them too large in firefox browser.
=> Delete unnecessary icon attributes

arbeitszeit/records.py, arbeitszeit/repositories.py, arbeitszeit/transfers/compensation.py, arbeitszeit/use_cases/get_company_summary.py, arbeitszeit/use_cases/query_company_consumptions.py, arbeitszeit/use_cases/register_private_consumption.py, arbeitszeit/use_cases/register_productive_consumption.py, arbeitszeit/use_cases/review_registered_consumptions.py, arbeitszeit/use_cases/show_p_account_details.py, arbeitszeit/use_cases/show_prd_account_details.py, arbeitszeit/use_cases/show_r_account_details.py, arbeitszeit_flask/database/models.py, arbeitszeit_flask/database/repositories.py, arbeitszeit_flask/migrations/versions/8b51e4ca0073_transfers_in_productive_consumption.py, tests/data_generators.py, tests/flask_integration/database_gateway_impl/test_productive_consumption_result.py, tests/services/test_compensation_transfer_service.py, tests/use_cases/repositories.py, tests/use_cases/test_register_private_consumption.py, tests/use_cases/test_register_productive_consumption.py, tests/use_cases/test_show_r_account_details.py
**Add CompensationTransferService** 
The service's `create_compensation_transfer` method can be used when registering private as well as productive consumptions.
**Transfers in RegisterProductiveConsumption (business logic)** 
Change the use case for registering productive consumptions to not create one transaction but to create up to two transfers: One consumption transfer and one optional compensation transfer.
This commit only implements business logic changes in `arbeitszeit` folder. Www layer and flask layer will follow in a seperate commit.
**Transfers in productive consumptions (Flask layer)** 
The alembic migration script has been tested successfully (upgrade/downgrade) manually with relevant data in database.
fixes #1239
=> Implement Transfers in Productive Consumptions

.github/workflows/python-app.yml, .readthedocs.yaml, docs/development_setup.rst, flake.nix, pyproject.toml
This commit deprecates Python 3.11. Instead, now we support Python 3.12 explicitly. Moreover, we support 3.13 implicitly (because channel nixpkgs-unstable currently uses Python 3.13.x).
=> Upgrade python 3.11 -> 3.12

arbeitszeit/records.py, arbeitszeit_flask/database/models.py, arbeitszeit_flask/database/repositories.py, arbeitszeit_flask/migrations/versions/4fd90069eb82_remove_social_accounting_account.py, tests/flask_integration/database_gateway_impl/test_account_result.py, tests/use_cases/repositories.py
- Delete dead code in records.py
- Delete general account of social accounting 
With the new transfer system social accounting needs only one "psf" account.
fixes #1268
=> Delete unused social accounting account

arbeitszeit_flask/accountant/routes.py, arbeitszeit_flask/company/routes.py, arbeitszeit_flask/member/routes.py, arbeitszeit_flask/user/routes.py, arbeitszeit_flask/views/coop_summary_view.py, arbeitszeit_web/www/presenters/get_company_summary_presenter.py, arbeitszeit_web/www/presenters/get_coop_summary_presenter.py, arbeitszeit_web/www/presenters/get_plan_details_accountant_presenter.py, arbeitszeit_web/www/presenters/get_plan_details_company_presenter.py, arbeitszeit_web/www/presenters/get_plan_details_member_presenter.py, arbeitszeit_web/www/presenters/query_companies_presenter.py
We can access the fields of a dataclass in a jinja template using the dot notation without having to convert it to a dictionary first.
=> Remove unneded dataclass conversions

arbeitszeit/use_cases/list_transfers.py, tests/services/test_compensation_transfer_service.py, tests/use_cases/base_test_case.py, tests/use_cases/test_approve_plan.py, tests/use_cases/test_list_transfers.py, tests/use_cases/test_register_private_consumption.py, tests/use_cases/test_register_productive_consumption.py
- Add database gateway to use case base test case
- Stricter boundaries for list transfer use case 
Instead of passing business objects (entities like Member or Company) from the ListTransfer use case to the presenter, pass specialized data transfer objects.
The downside is more parsing and mapping necessary, the upside is clearer boundaries between presenter and business logic.
Anonymization of workers' names, ids and account ids is now done in the use case instead of the presenter.
For context see #1242
=> Change response object of ListTransferUseCase

arbeitszeit/interactors/get_coop_summary.py, arbeitszeit/interactors/query_plans.py, arbeitszeit/interactors/register_private_consumption.py, arbeitszeit/interactors/register_productive_consumption.py, arbeitszeit/interactors/show_my_plans.py, arbeitszeit/records.py, arbeitszeit/services/plan_details.py, arbeitszeit/services/price_calculator.py, arbeitszeit_flask/database/repositories.py, arbeitszeit_web/www/presenters/show_my_plans_presenter.py, tests/data_generators.py, tests/flask_integration/database_gateway_impl/test_plan_results.py, tests/interactors/repositories.py, tests/records/test_plan.py, tests/services/test_price_calculator.py, tests/www/presenters/test_show_my_plans_presenter.py
This PR consists of several commits. The main goal was to reduce the dependency of our tests from complex business logic objects (records) - in this case the `Plan` record. This dependency has been replaced with a dependency on the plan id. This was done to protect our tests from changes in the business records.
Along the way there has been some refactoring, a slight change in how the cooperation price is calculated and a well-hidden bug in the Plan repository has been fixed.
=> Reduce test dependency on business records

arbeitszeit/anonymization.py, arbeitszeit/interactors/get_member_account.py, arbeitszeit/interactors/show_prd_account_details.py, arbeitszeit/services/account_details.py, arbeitszeit_flask/database/repositories.py, arbeitszeit_flask/templates/macros/transfers.html, arbeitszeit_flask/templates/member/my_account.html, arbeitszeit_flask/templates/user/company_account_a.html, arbeitszeit_flask/templates/user/company_account_p.html, arbeitszeit_flask/templates/user/company_account_prd.html, arbeitszeit_flask/templates/user/company_account_r.html, arbeitszeit_web/www/presenters/get_member_account_presenter.py, arbeitszeit_web/www/presenters/list_transfers_presenter.py, arbeitszeit_web/www/presenters/show_a_account_details_presenter.py, arbeitszeit_web/www/presenters/show_p_account_details_presenter.py, arbeitszeit_web/www/presenters/show_prd_account_details_presenter.py, arbeitszeit_web/www/presenters/show_r_account_details_presenter.py, arbeitszeit_web/www/presenters/transfers.py, tests/data_generators.py, tests/interactors/test_get_member_account.py, tests/interactors/test_show_prd_account_details.py, tests/services/test_account_details_service.py, tests/www/presenters/test_get_member_account_presenter.py, tests/www/presenters/test_list_transfers_presenter.py, tests/www/presenters/test_show_a_account_details_presenter.py, tests/www/presenters/test_show_p_account_details_presenter.py, tests/www/presenters/test_show_prd_account_details_presenter.py, tests/www/presenters/test_show_r_account_details.py
The main purpose of this Pull Request is to unify account transfer display logic across different accounts (company p, r, a and member accounts).
One motivation was to reduce code duplication, because we want to display transfers similarily in all accounts, probably also in the future.
The second motiviation was to simplify the upcoming implementation of the transfer reversal logic. Now it will be easier to program (and test) the display of the new reversal transfers in the different accounts - see issue #825.
Note that performances of some use cases have dropped because we are now providing more complex data via db joins in some interactors: 
- benchmark "show_r_account_details": master: 0.0264, this branch: 0.0780 seconds
- benchmark "show_prd_account_details": master: 0.1357, this …
=> Reduce code duplication in transfer display
